import { IFormulaCarier, IFormulaOrientation, IFormulaProgram } from "../interfaces/formula-carier.interface";

export const formulaOrientationData: IFormulaOrientation[] = [
    { category: 'DATA_MANUSIA-DATA_MANUSIA', persentage: 85 },
    { category: 'DATA_MANUSIA-DATA_MANUSIA-DATA_MANUSIA', persentage: 100 },
    { category: 'DATA_MANUSIA-DATA_MANUSIA-DATA_TEKNOLOGI', persentage: 65 },
    { category: 'DATA_MANUSIA-MANUSIA_TEKNOLOGI', persentage: 85 },
    { category: 'DATA_MANUSIA-IDE_MANUSIA', persentage: 65 },
    { category: 'DATA_MANUSIA-MANUSIA_TEKNOLOGI-DATA_TEKNOLOGI', persentage: 65 },
    { category: 'DATA_MANUSIA-IDE_TEKNOLOGI', persentage: 40 },
    { category: 'DATA_MANUSIA-DATA_TEKNOLOGI', persentage: 40 },

    { category: 'DATA_TEKNOLOGI-DATA_MANUSIA', persentage: 85 },
    { category: 'DATA_TEKNOLOGI-DATA_MANUSIA-DATA_MANUSIA', persentage: 65 },
    { category: 'DATA_TEKNOLOGI-DATA_MANUSIA-DATA_TEKNOLOGI', persentage: 100 },
    { category: 'DATA_TEKNOLOGI-MANUSIA_TEKNOLOGI', persentage: 50 },
    { category: 'DATA_TEKNOLOGI-IDE_MANUSIA', persentage: 25 },
    { category: 'DATA_TEKNOLOGI-MANUSIA_TEKNOLOGI-DATA_TEKNOLOGI', persentage: 65 },
    { category: 'DATA_TEKNOLOGI-IDE_TEKNOLOGI', persentage: 65 },
    { category: 'DATA_TEKNOLOGI-DATA_TEKNOLOGI', persentage: 85 },

    { category: 'IDE_MANUSIA-DATA_MANUSIA', persentage: 40 },
    { category: 'IDE_MANUSIA-DATA_MANUSIA-DATA_MANUSIA', persentage: 65 },
    { category: 'IDE_MANUSIA-DATA_MANUSIA-DATA_TEKNOLOGI', persentage: 25 },
    { category: 'IDE_MANUSIA-MANUSIA_TEKNOLOGI', persentage: 85 },
    { category: 'IDE_MANUSIA-IDE_MANUSIA', persentage: 100 },
    { category: 'IDE_MANUSIA-MANUSIA_TEKNOLOGI-DATA_TEKNOLOGI', persentage: 65 },
    { category: 'IDE_MANUSIA-IDE_TEKNOLOGI', persentage: 65 },
    { category: 'IDE_MANUSIA-DATA_TEKNOLOGI', persentage: 25 },

    { category: 'MANUSIA_TEKNOLOGI-DATA_MANUSIA', persentage: 40 },
    { category: 'MANUSIA_TEKNOLOGI-DATA_MANUSIA-DATA_MANUSIA', persentage: 40 },
    { category: 'MANUSIA_TEKNOLOGI-DATA_MANUSIA-DATA_TEKNOLOGI', persentage: 65 },
    { category: 'MANUSIA_TEKNOLOGI-MANUSIA_TEKNOLOGI', persentage: 85 },
    { category: 'MANUSIA_TEKNOLOGI-IDE_MANUSIA', persentage: 65 },
    { category: 'MANUSIA_TEKNOLOGI-MANUSIA_TEKNOLOGI-DATA_TEKNOLOGI', persentage: 100 },
    { category: 'MANUSIA_TEKNOLOGI-IDE_TEKNOLOGI', persentage: 65 },
    { category: 'MANUSIA_TEKNOLOGI-DATA_TEKNOLOGI', persentage: 85 },

    { category: 'IDE_TEKNOLOGI-DATA_MANUSIA', persentage: 40 },
    { category: 'IDE_TEKNOLOGI-DATA_MANUSIA-DATA_MANUSIA', persentage: 40 },
    { category: 'IDE_TEKNOLOGI-DATA_MANUSIA-DATA_TEKNOLOGI', persentage: 65 },
    { category: 'IDE_TEKNOLOGI-MANUSIA_TEKNOLOGI', persentage: 50 },
    { category: 'IDE_TEKNOLOGI-IDE_MANUSIA', persentage: 65 },
    { category: 'IDE_TEKNOLOGI-MANUSIA_TEKNOLOGI-DATA_TEKNOLOGI', persentage: 65 },
    { category: 'IDE_TEKNOLOGI-IDE_TEKNOLOGI', persentage: 100 },
    { category: 'IDE_TEKNOLOGI-DATA_TEKNOLOGI', persentage: 85 }
];

export const formulaCarierData: IFormulaCarier[] = [
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Sosial",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Administrasi Bisnis",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Sosial",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Administrasi Bisnis",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Sosial",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Administrasi Bisnis",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Sosial",
        codeSDS: "IE",
        code1: "I",
        code2: "E",
        program: "S1 Administrasi Bisnis",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Sosial",
        codeSDS: "EI",
        code1: "E",
        code2: "I",
        program: "S1 Administrasi Bisnis",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Sosial",
        codeSDS: "SE",
        code1: "S",
        code2: "E",
        program: "S1 Administrasi Bisnis",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Sosial",
        codeSDS: "ES",
        code1: "E",
        code2: "S",
        program: "S1 Administrasi Bisnis",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Akuntansi",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Akuntansi",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Akuntansi",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Akuntansi",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Bisnis Digital",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Bisnis Digital",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Bisnis Digital",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Bisnis Digital",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Desain Interior",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Desain Interior",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Desain Interior",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Desain Interior",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "AS",
        code1: "A",
        code2: "S",
        program: "S1 Desain Interior",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "SA",
        code1: "S",
        code2: "A",
        program: "S1 Desain Interior",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Desain Produk & Inovasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Desain Produk & Inovasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Desain Produk & Inovasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "IA",
        code1: "I",
        code2: "A",
        program: "S1 Desain Produk & Inovasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "AI",
        code1: "A",
        code2: "I",
        program: "S1 Desain Produk & Inovasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Film dan Animasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Film dan Animasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "AC",
        code1: "A",
        code2: "C",
        program: "S1 Film dan Animasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Film dan Animasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "AS",
        code1: "A",
        code2: "S",
        program: "S1 Film dan Animasi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Digital Public Relations",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Digital Public Relations",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "SA",
        code1: "S",
        code2: "A",
        program: "S1 Digital Public Relations",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "AS",
        code1: "A",
        code2: "S",
        program: "S1 Digital Public Relations",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "ES",
        code1: "E",
        code2: "S",
        program: "S1 Digital Public Relations",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "SE",
        code1: "S",
        code2: "E",
        program: "S1 Digital Public Relations",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Sosial",
        cluster3: "Manajemen",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Ilmu Komunikasi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Sosial",
        cluster3: "Manajemen",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Ilmu Komunikasi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Sosial",
        cluster3: "Manajemen",
        codeSDS: "SA",
        code1: "S",
        code2: "A",
        program: "S1 Ilmu Komunikasi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Sosial",
        cluster3: "Manajemen",
        codeSDS: "AS",
        code1: "A",
        code2: "S",
        program: "S1 Ilmu Komunikasi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Sosial",
        cluster3: "Manajemen",
        codeSDS: "IS",
        code1: "I",
        code2: "S",
        program: "S1 Ilmu Komunikasi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Sosial",
        cluster3: "Manajemen",
        codeSDS: "SI",
        code1: "S",
        code2: "I",
        program: "S1 Ilmu Komunikasi",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Informatika",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Informatika",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Informatika",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Informatika",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Informatika",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Informatika",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Manajemen",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Kriya (Fashion and Textile Design)",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Manajemen",
        codeSDS: "AC",
        code1: "A",
        code2: "C",
        program: "S1 Kriya (Fashion and Textile Design)",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Manajemen",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Kriya (Fashion and Textile Design)",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Manajemen",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Kriya (Fashion and Textile Design)",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Manajemen",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Kriya (Fashion and Textile Design)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "IE",
        code1: "I",
        code2: "E",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "EI",
        code1: "E",
        code2: "I",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Leisure Management",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "SI",
        code1: "S",
        code2: "I",
        program: "S1 Leisure Management",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "IS",
        code1: "I",
        code2: "S",
        program: "S1 Leisure Management",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Leisure Management",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Leisure Management",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Leisure Management",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Leisure Management",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "D3 Digital Marketing",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "D3 Digital Marketing",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "D3 Digital Marketing",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "CA",
        code1: "C",
        code2: "A",
        program: "D3 Digital Marketing",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "D3 Digital Marketing",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "ES",
        code1: "E",
        code2: "S",
        program: "D3 Digital Marketing",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "SE",
        code1: "S",
        code2: "E",
        program: "D3 Digital Marketing",
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Manajemen Rekayasa Industri",
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Manajemen Rekayasa Industri",
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Manajemen Rekayasa Industri",
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Manajemen Rekayasa Industri",
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Manajemen Rekayasa Industri",
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Manajemen Rekayasa Industri",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Komunikasi",
        cluster2: "Desain",
        cluster3: "Teknologi Informasi",
        codeSDS: "AC",
        code1: "A",
        code2: "C",
        program: "S1 Digital Content Broadcasting",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Komunikasi",
        cluster2: "Desain",
        cluster3: "Teknologi Informasi",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Digital Content Broadcasting",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Komunikasi",
        cluster2: "Desain",
        cluster3: "Teknologi Informasi",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Digital Content Broadcasting",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Komunikasi",
        cluster2: "Desain",
        cluster3: "Teknologi Informasi",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Digital Content Broadcasting",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Komunikasi",
        cluster2: "Desain",
        cluster3: "Teknologi Informasi",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Digital Content Broadcasting",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Komunikasi",
        cluster2: "Desain",
        cluster3: "Teknologi Informasi",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Digital Content Broadcasting",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Komunikasi",
        cluster2: "Desain",
        cluster3: "Teknologi Informasi",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Digital Content Broadcasting",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "D3 Hospitality and Culinary Art",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "D3 Hospitality and Culinary Art",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "CS",
        code1: "C",
        code2: "S",
        program: "D3 Hospitality and Culinary Art",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "SE",
        code1: "S",
        code2: "E",
        program: "D3 Hospitality and Culinary Art",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "IS",
        code1: "I",
        code2: "S",
        program: "S1 Psikologi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Psikologi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Psikologi"
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "SI",
        code1: "S",
        code2: "I",
        program: "S1 Psikologi"
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "SC",
        code1: "S",
        code2: "C",
        program: "S1 Psikologi"
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "SE",
        code1: "S",
        code2: "E",
        program: "S1 Psikologi"
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "AS",
        code1: "A",
        code2: "S",
        program: "S1 Psikologi"
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "SA",
        code1: "S",
        code2: "A",
        program: "S1 Psikologi"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Rekayasa Perangkat Lunak"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "AI",
        code1: "A",
        code2: "I",
        program: "S1 Rekayasa Perangkat Lunak"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IA",
        code1: "I",
        code2: "A",
        program: "S1 Rekayasa Perangkat Lunak"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Rekayasa Perangkat Lunak"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IA",
        code1: "I",
        code2: "A",
        program: "S1 Rekayasa Perangkat Lunak"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Rekayasa Perangkat Lunak"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Rekayasa Perangkat Lunak"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Data Sains"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Data Sains"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Data Sains"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Data Sains"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Data Sains"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Data Sains"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Creative Arts (Intermedia Visual Arts)"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Creative Arts (Intermedia Visual Arts)"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Creative Arts (Intermedia Visual Arts)"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Creative Arts (Intermedia Visual Arts)"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "SA",
        code1: "S",
        code2: "A",
        program: "S1 Creative Arts (Intermedia Visual Arts)"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Komputer",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Sistem Informasi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Komputer",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Sistem Informasi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Komputer",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Sistem Informasi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Komputer",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Sistem Informasi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Komputer",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Sistem Informasi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Komputer",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Sistem Informasi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "D3 Sistem Informasi Akuntansi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "D3 Sistem Informasi Akuntansi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "D3 Sistem Informasi Akuntansi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "D3 Sistem Informasi Akuntansi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "D3 Sistem Informasi Akuntansi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "D3 Sistem Informasi Akuntansi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "D4 Sistem Informasi Kota Cerdas"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "D4 Sistem Informasi Kota Cerdas"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "D4 Sistem Informasi Kota Cerdas"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "D4 Sistem Informasi Kota Cerdas"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "D4 Sistem Informasi Kota Cerdas"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "D4 Sistem Informasi Kota Cerdas"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Kesehatan",
        cluster3: "Komputer",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Teknik Biomedis"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Kesehatan",
        cluster3: "Komputer",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Teknik Biomedis"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Kesehatan",
        cluster3: "Komputer",
        codeSDS: "SI",
        code1: "S",
        code2: "I",
        program: "S1 Teknik Biomedis"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Kesehatan",
        cluster3: "Komputer",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Teknik Biomedis"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Kesehatan",
        cluster3: "Komputer",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Teknik Biomedis"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Kesehatan",
        cluster3: "Komputer",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Teknik Biomedis"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Teknik Elektro"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Teknik Elektro"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Teknik Elektro"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Teknik Elektro"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Teknik Elektro"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Teknik Elektro"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Teknik",
        cluster3: "Manajemen",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Smart Science and Technology"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Teknik",
        cluster3: "Manajemen",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Smart Science and Technology"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Teknik",
        cluster3: "Manajemen",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Smart Science and Technology"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Teknik",
        cluster3: "Manajemen",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Smart Science and Technology"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Teknik",
        cluster3: "Manajemen",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Smart Science and Technology"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Teknik",
        cluster3: "Manajemen",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Smart Science and Technology"
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Teknik Industri"
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Teknik Industri"
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Teknik Industri"
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Teknik Industri"
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "IE",
        code1: "I",
        code2: "E",
        program: "S1 Teknik Industri"
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "EI",
        code1: "E",
        code2: "I",
        program: "S1 Teknik Industri"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Komputer",
        cluster3: "Teknologi Informasi",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Teknik Komputer"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Komputer",
        cluster3: "Teknologi Informasi",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Teknik Komputer"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Komputer",
        cluster3: "Teknologi Informasi",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Teknik Komputer"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Komputer",
        cluster3: "Teknologi Informasi",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Teknik Komputer"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Komputer",
        cluster3: "Teknologi Informasi",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Teknik Komputer"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Komputer",
        cluster3: "Teknologi Informasi",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Teknik Komputer"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Teknologi Informasi",
        cluster3: "Bisnis",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Digital Supply Chain"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Teknologi Informasi",
        cluster3: "Bisnis",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Digital Supply Chain"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Teknologi Informasi",
        cluster3: "Bisnis",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Digital Supply Chain"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Teknologi Informasi",
        cluster3: "Bisnis",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Digital Supply Chain"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Teknologi Informasi",
        cluster3: "Bisnis",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Digital Supply Chain"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Teknologi Informasi",
        cluster3: "Bisnis",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Digital Supply Chain"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Teknologi Informasi",
        cluster3: "Bisnis",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Digital Supply Chain"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Electrical Energy Engineering"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Electrical Energy Engineering"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Electrical Energy Engineering"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Electrical Energy Engineering"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Electrical Energy Engineering"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Electrical Energy Engineering"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Teknik Telekomunikasi",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Teknik Telekomunikasi",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Teknik Telekomunikasi",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Teknik Telekomunikasi",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Teknik Telekomunikasi",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Teknik Telekomunikasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Teknologi Pangan",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Teknologi Pangan",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "IS",
        code1: "I",
        code2: "S",
        program: "S1 Teknologi Pangan",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "SI",
        code1: "S",
        code2: "I",
        program: "S1 Teknologi Pangan",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "ER",
        code1: "E",
        code2: "R",
        program: "S1 Teknologi Pangan",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "RE",
        code1: "R",
        code2: "E",
        program: "S1 Teknologi Pangan",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Seni",
        codeSDS: "AI",
        code1: "A",
        code2: "I",
        program: "S1 Terapan Digital Creative Multimedia (DCM)",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Seni",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Terapan Digital Creative Multimedia (DCM)",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Seni",
        codeSDS: "AC",
        code1: "A",
        code2: "C",
        program: "S1 Terapan Digital Creative Multimedia (DCM)",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Seni",
        codeSDS: "IA",
        code1: "I",
        code2: "A",
        program: "S1 Terapan Digital Creative Multimedia (DCM)",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Seni",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Terapan Digital Creative Multimedia (DCM)",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Seni",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Terapan Digital Creative Multimedia (DCM)",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Desain Komunikasi Visual",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Desain Komunikasi Visual",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Desain Komunikasi Visual",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Desain Komunikasi Visual",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "AS",
        code1: "A",
        code2: "S",
        program: "S1 Desain Komunikasi Visual",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "SA",
        code1: "S",
        code2: "A",
        program: "S1 Desain Komunikasi Visual",
    }
]

export const formulaProgramData: IFormulaProgram[] = [
    { mbti: "INTP-R", program: "D3 Digital Marketing" },
    { mbti: "INTP-R", program: "S1 Informatika" },
    { mbti: "INTP-R", program: "S1 Teknik Komputer" },
    { mbti: "INTP-R", program: "S1 Teknik Elektro" },
    { mbti: "INTP-R", program: "S1 Teknik Industri" },
    { mbti: "INTP-R", program: "S1 Rekayasa Perangkat Lunak" },
    { mbti: "INTP-I", program: "S1 Data Sains" },
    { mbti: "INTP-I", program: "S1 Sistem Informasi" },
    { mbti: "INTP-I", program: "S1 Psikologi" },
    { mbti: "INTP-I", program: "S1 Teknik Biomedis" },
    { mbti: "INTP-I", program: "S1 Electrical Energy Engineering" },
    { mbti: "INTP-I", program: "S1 Smart Science and Technology" },
    { mbti: "INTP-I", program: "S1 Ilmu Komunikasi" },
    { mbti: "INTP-I", program: "S1 Digital Content Broadcasting" },
    { mbti: "INTP-A", program: "S1 Desain Komunikasi Visual" },
    { mbti: "INTP-A", program: "S1 Desain Interior" },
    { mbti: "INTP-A", program: "S1 Kriya (Fashion and Textile Design)" },
    { mbti: "INTP-A", program: "S1 Film dan Animasi" },
    { mbti: "INTP-A", program: "S1 Creative Arts" },
    { mbti: "INTP-S", program: "S1 Psikologi" },
    { mbti: "INTP-S", program: "S1 Ilmu Komunikasi" },
    { mbti: "INTP-S", program: "S1 Digital Public Relations" },
    { mbti: "INTP-E", program: "S1 Administrasi Bisnis" },
    { mbti: "INTP-E", program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)" },
    { mbti: "INTP-E", program: "S1 Bisnis Digital" },
    { mbti: "INTP-E", program: "S1 Digital Marketing" },
    { mbti: "INTJ-R", program: "S1 Teknik Komputer" },
    { mbti: "INTJ-R", program: "S1 Teknik Elektro" },
    { mbti: "INTJ-R", program: "S1 Teknik Biomedis" },
    { mbti: "INTJ-R", program: "D3 Sistem Informasi Akuntansi" },
    { mbti: "INTJ-R", program: "S1 Digital Supply Chain" },
    { mbti: "INTJ-I", program: "S1 Data Sains" },
    { mbti: "INTJ-I", program: "S1 Sistem Informasi" },
    { mbti: "INTJ-I", program: "S1 Psikologi" },
    { mbti: "INTJ-I", program: "S1 Ilmu Komunikasi" },
    { mbti: "INTJ-I", program: "S1 Teknologi Pangan" },
    { mbti: "INTJ-I", program: "S1 Teknik Industri" },
    { mbti: "INTJ-A", program: "S1 Desain Komunikasi Visual" },
    { mbti: "INTJ-A", program: "S1 Film dan Animasi" },
    { mbti: "INTJ-A", program: "S1 Desain Produk & Inovasi" },
    { mbti: "INTJ-A", program: "S1 Desain Interior" },
    { mbti: "INTJ-S", program: "S1 Psikologi" },
    { mbti: "INTJ-S", program: "S1 Ilmu Komunikasi" },
    { mbti: "INTJ-S", program: "S1 Digital Public Relations" },
    { mbti: "INTJ-E", program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)" },
    { mbti: "INTJ-E", program: "S1 Administrasi Bisnis" },
    { mbti: "INTJ-E", program: "S1 Bisnis Digital" },
    { mbti: "INTJ-C", program: "S1 Akuntansi" },
    { mbti: "INTJ-C", program: "D3 Sistem Informasi Akuntansi" },
    { mbti: "INFJ-I", program: "S1 Psikologi" },
    { mbti: "INFJ-I", program: "S1 Ilmu Komunikasi" },
    { mbti: "INFJ-I", program: "S1 Data Sains" },
    { mbti: "INFJ-I", program: "S1 Teknologi Pangan" },
    { mbti: "INFJ-I", program: "S1 Sistem Informasi" },
    { mbti: "INFJ-A", program: "S1 Desain Komunikasi Visual" },
    { mbti: "INFJ-A", program: "S1 Film dan Animasi" },
    { mbti: "INFJ-A", program: "S1 Desain Produk & Inovasi" },
    { mbti: "INFJ-A", program: "S1 Kriya (Fashion and Textile Design)" },
    { mbti: "INFJ-S", program: "S1 Psikologi" },
    { mbti: "INFJ-S", program: "S1 Ilmu Komunikasi" },
    { mbti: "INFJ-S", program: "S1 Digital Public Relations" },
    { mbti: "INFJ-S", program: "S1 Administrasi Bisnis" },
    { mbti: "INFJ-E", program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)" },
    { mbti: "INFJ-E", program: "S1 Bisnis Digital" },
    { mbti: "INFJ-C", program: "S1 Akuntansi" },
    { mbti: "INFJ-C", program: "D3 Sistem Informasi Akuntansi" },
    { mbti: "INFJ-C", program: "D3 Digital Marketing" },
    { mbti: "ENFP-R", program: "S1 Desain Produk & Inovasi" },
    { mbti: "ENFP-R", program: "S1 Teknik Industri" },
    { mbti: "ENFP-R", program: "S1 Teknik Komputer" },
    { mbti: "ENFP-R", program: "S1 Teknik Telekomunikasi" },
    { mbti: "ENFP-R", program: "S1 Teknik Elektro" },
    { mbti: "ENFP-R", program: "S1 Teknik Biomedis" },
    { mbti: "ENFP-I", program: "S1 Psikologi" },
    { mbti: "ENFP-I", program: "S1 Data Sains" },
    { mbti: "ENFP-I", program: "S1 Sistem Informasi" },
    { mbti: "ENFP-I", program: "D4 Sistem Informasi Kota Cerdas" },
    { mbti: "ENFP-I", program: "S1 Smart Science and Technology" },
    { mbti: "ENFP-A", program: "S1 Desain Komunikasi Visual" },
    { mbti: "ENFP-A", program: "S1 Kriya (Fashion and Textile Design)" },
    { mbti: "ENFP-A", program: "S1 Film dan Animasi" },
    { mbti: "ENFP-A", program: "S1 Creative Arts (Intermedia Visual Arts)" },
    { mbti: "ENFP-A", program: "S1 Desain Interior" },
    { mbti: "ENFP-S", program: "S1 Ilmu Komunikasi" },
    { mbti: "ENFP-S", program: "S1 Digital Public Relations" },
    { mbti: "ENFP-S", program: "S1 Administrasi Bisnis" },
    { mbti: "ENFP-S", program: "S1 Psikologi" },
    { mbti: "ENFP-S", program: "D3 Hospitality and Culinary Art" },
    { mbti: "ENFP-E", program: "S1 Bisnis Digital" },
    { mbti: "ENFP-E", program: "S1 Digital Marketing" },
    { mbti: "ENFP-E", program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)" },
    { mbti: "ENFP-E", program: "S1 Leisure Management" },
    { mbti: "ENFP-E", program: "S1 Akuntansi" },
    { mbti: "ENFP-C", program: "D3 Sistem Informasi Akuntansi" },
    { mbti: "ENFP-C", program: "S1 Akuntansi" },
    { mbti: "ENFP-C", program: "S1 Digital Supply Chain" },
    { mbti: "INFP-R", program: "S1 Teknologi Pangan" },
    { mbti: "INFP-R", program: "S1 Desain Produk & Inovasi" },
    { mbti: "INFP-R", program: "S1 Leisure Management" },
    { mbti: "INFP-I", program: "S1 Psikologi" },
    { mbti: "INFP-I", program: "S1 Ilmu Komunikasi" },
    { mbti: "INFP-A", program: "S1 Desain Interior" },
    { mbti: "INFP-A", program: "S1 Desain Komunikasi Visual" },
    { mbti: "INFP-A", program: "S1 Kriya (Fashion and Textile Design)" },
    { mbti: "INFP-A", program: "S1 Terapan Digital Creative Multimedia (DCM)" },
    { mbti: "INFP-A", program: "S1 Film dan Animasi" },
    { mbti: "INFP-A", program: "S1 Creative Arts (Intermedia Visual Arts)" },
    { mbti: "INFP-A", program: "S1 Desain Produk & Inovasi" },
    { mbti: "INFP-S", program: "S1 Psikologi" },
    { mbti: "INFP-S", program: "S1 Ilmu Komunikasi" },
    { mbti: "INFP-S", program: "D3 Hospitality and Culinary Art" },
    { mbti: "INFP-E", program: "S1 Administrasi Bisnis" },
    { mbti: "INFP-E", program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)" },
    { mbti: "INFP-E", program: "S1 Bisnis Digital" },
    { mbti: "INFP-E", program: "S1 Ilmu Komunikasi" },
    { mbti: "ISTJ-R", program: "D3 Hospitality and Culinary Art" },
    { mbti: "ISTJ-R", program: "S1 Manajemen Rekayasa Industri" },
    { mbti: "ISTJ-R", program: "S1 Teknik Industri" },
    { mbti: "ISTJ-R", program: "S1 Teknik Elektro" },
    { mbti: "ISTJ-I", program: "S1 Psikologi" },
    { mbti: "ISTJ-I", program: "S1 Ilmu Komunikasi" },
    { mbti: "ISTJ-I", program: "S1 Data Sains" },
    { mbti: "ISTJ-I", program: "S1 Sistem Informasi" },
    { mbti: "ISTJ-I", program: "S1 Smart Science and Technology" },
    { mbti: "ISTJ-I", program: "S1 Teknik Biomedis" },
    { mbti: "ISTJ-I", program: "S1 Teknik Komputer" },
    { mbti: "ISTJ-C", program: "S1 Akuntansi" },
    { mbti: "ISTJ-C", program: "D3 Sistem Informasi Akuntansi" },
    { mbti: "ISTJ-C", program: "S1 Administrasi Bisnis" },
    { mbti: "ISTJ-C", program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)" },
    { mbti: "ISTJ-C", program: "S1 Rekayasa Perangkat Lunak" },
    { mbti: "ISTJ-C", program: "S1 Sistem Informasi" },
    { mbti: "ISTJ-C", program: "S1 Teknologi Informasi" },
    { mbti: "ISFP-R", program: "D3 Hospitality and Culinary Art" },
    { mbti: "ISFP-R", program: "S1 Desain Interior" },
    { mbti: "ISFP-R", program: "S1 Teknologi Pangan" },
    { mbti: "ISFP-R", program: "S1 Manajemen Rekayasa Industri" },
    { mbti: "ISFP-R", program: "S1 Teknik Industri" },
    { mbti: "ISFP-I", program: "S1 Teknik Biomedis" },
    { mbti: "ISFP-I", program: "S1 Psikologi" },
    { mbti: "ISFP-A", program: "S1 Desain Interior" },
    { mbti: "ISFP-A", program: "S1 Desain Komunikasi Visual" },
    { mbti: "ISFP-A", program: "S1 Kriya (Fashion and Textile Design)" },
    { mbti: "ISFP-A", program: "S1 Terapan Digital Creative Multimedia (DCM)" },
    { mbti: "ISFP-A", program: "S1 Film dan Animasi" },
    { mbti: "ISFP-A", program: "S1 Creative Arts (Intermedia Visual Arts)" },
    { mbti: "ISFP-S", program: "S1 Psikologi" },
    { mbti: "ISFP-S", program: "D3 Hospitality and Culinary Art" },
    { mbti: "ISFP-S", program: "S1 Ilmu Komunikasi" },
    { mbti: "ISFP-E", program: "S1 Administrasi Bisnis" },
    { mbti: "ISFP-E", program: "S1 Digital Marketing" },
    { mbti: "ISFP-E", program: "S1 Bisnis Digital" },
    { mbti: "ISFP-E", program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)" },
    { mbti: "ISFJ-R", program: "D3 Hospitality and Culinary Art" },
    { mbti: "ISFJ-A", program: "S1 Desain Interior" },
    { mbti: "ISFJ-A", program: "S1 Desain Komunikasi Visual" },
    { mbti: "ISFJ-A", program: "S1 Kriya (Fashion and Textile Design)" },
    { mbti: "ISFJ-A", program: "S1 Terapan Digital Creative Multimedia (DCM)" },
    { mbti: "ISFJ-A", program: "S1 Film dan Animasi" },
    { mbti: "ISFJ-A", program: "S1 Creative Arts (Intermedia Visual Arts)" },
    { mbti: "ISFJ-S", program: "S1 Psikologi" },
    { mbti: "ISFJ-S", program: "D3 Hospitality and Culinary Art" },
    { mbti: "ISFJ-S", program: "S1 Ilmu Komunikasi" },
    { mbti: "ISFJ-E", program: "S1 Administrasi Bisnis" },
    { mbti: "ISFJ-E", program: "S1 Digital Marketing" },
    { mbti: "ISFJ-E", program: "S1 Bisnis Digital" },
    { mbti: "ISFJ-C", program: "S1 Akuntansi" },
    { mbti: "ISFJ-C", program: "S1 Administrasi Bisnis" },
    { mbti: "ISTP-R", program: "D3 Hospitality and Culinary Art" },
    { mbti: "ISTP-R", program: "S1 Manajemen Rekayasa Industri" },
    { mbti: "ISTP-R", program: "S1 Teknik Elektro" },
    { mbti: "ISTP-R", program: "S1 Teknik Industri" },
    { mbti: "ISTP-I", program: "S1 Teknik Biomedis" },
    { mbti: "ISTP-I", program: "S1 Psikologi" },
    { mbti: "ISTP-I", program: "S1 Ilmu Komunikasi" },
    { mbti: "ISTP-I", program: "S1 Teknik Komputer" },
    { mbti: "ISTP-A", program: "S1 Desain Produk & Inovasi" },
    { mbti: "ISTP-A", program: "S1 Terapan Digital Creative Multimedia (DCM)" },
    { mbti: "ISTP-S", program: "S1 Psikologi" },
    { mbti: "ISTP-S", program: "S1 Ilmu Komunikasi" },
    { mbti: "ISTP-E", program: "S1 Administrasi Bisnis" },
    { mbti: "ISTP-E", program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)" },
    { mbti: "ENTP-R", program: "D3 Digital Marketing" },
    { mbti: "ENTP-R", program: "S1 Teknik Elektro" },
    { mbti: "ENTP-R", program: "S1 Teknik Komputer" },
    { mbti: "ENTP-R", program: "S1 Teknik Industri" },
    { mbti: "ENTP-I", program: "S1 Data Sains" },
    { mbti: "ENTP-I", program: "S1 Sistem Informasi" },
    { mbti: "ENTP-I", program: "S1 Rekayasa Perangkat Lunak" },
    { mbti: "ENTP-I", program: "S1 Psikologi" },
    { mbti: "ENTP-I", program: "S1 Biomedis" },
    { mbti: "ENTP-A", program: "S1 Desain Komunikasi Visual" },
    { mbti: "ENTP-A", program: "S1 Desain Interior" },
    { mbti: "ENTP-A", program: "S1 Kriya" },
    { mbti: "ENTP-A", program: "S1 Film dan Animasi" },
    { mbti: "ENTP-A", program: "S1 Creative Arts" },
    { mbti: "ENTP-S", program: "S1 Psikologi" },
    { mbti: "ENTP-S", program: "S1 Ilmu Komunikasi" },
    { mbti: "ENTP-S", program: "S1 Digital Public Relations" },
    { mbti: "ENTP-S", program: "D3 Hospitality and Culinary Art" },
    { mbti: 'ENTP-E', program: 'S1 Administrasi Bisnis' },
    { mbti: 'ENTP-E', program: 'S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)' },
    { mbti: 'ENTP-E', program: 'S1 Bisnis Digital' },
    { mbti: 'ENTP-E', program: 'S1 Smart Science and Technology' },
    { mbti: 'ENTP-E', program: 'S1 Digital Content Broadcasting' },
    { mbti: 'ENTP-C', program: 'S1 Akuntansi' },
    { mbti: 'ENTP-C', program: 'D3 Sistem Informasi Akuntansi' },
    { mbti: 'ENFJ-R', program: 'S1 Teknik Elektro' },
    { mbti: 'ENFJ-R', program: 'S1 Teknik Komputer' },
    { mbti: 'ENFJ-R', program: 'S1 Teknik Industri' },
    { mbti: 'ENFJ-I', program: 'S1 Data Sains' },
    { mbti: 'ENFJ-I', program: 'S1 Sistem Informasi' },
    { mbti: 'ENFJ-I', program: 'S1 Rekayasa Perangkat Lunak' },
    { mbti: 'ENFJ-I', program: 'S1 Psikologi' },
    { mbti: 'ENFJ-I', program: 'S1 Biomedis' },
    { mbti: 'ENFJ-A', program: 'S1 Desain Komunikasi Visual' },
    { mbti: 'ENFJ-A', program: 'S1 Desain Interior' },
    { mbti: 'ENFJ-A', program: 'S1 Kriya' },
    { mbti: 'ENFJ-A', program: 'S1 Film dan Animasi' },
    { mbti: 'ENFJ-A', program: 'S1 Creative Arts' },
    { mbti: 'ENFJ-S', program: 'S1 Psikologi' },
    { mbti: 'ENFJ-S', program: 'S1 Ilmu Komunikasi' },
    { mbti: 'ENFJ-S', program: 'S1 Digital Public Relations' },
    { mbti: 'ENFJ-S', program: 'D3 Hospitality and Culinary Art' },
    { mbti: 'ENFJ-S', program: 'S1 Leisure Management' },
    { mbti: 'ENFJ-E', program: 'S1 Administrasi Bisnis' },
    { mbti: 'ENFJ-E', program: 'S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)' },
    { mbti: 'ENFJ-E', program: 'S1 Bisnis Digital' },
    { mbti: 'ENFJ-E', program: 'S1 Smart Science and Technology' },
    { mbti: 'ENFJ-C', program: 'S1 Akuntansi' },
    { mbti: 'ENFJ-C', program: 'D3 Sistem Informasi Akuntansi' },
    { mbti: 'ENTJ-R', program: 'S1 Teknik Elektro' },
    { mbti: 'ENTJ-R', program: 'S1 Teknik Industri' },
    { mbti: 'ENTJ-R', program: 'S1 Teknik Komputer' },
    { mbti: 'ENTJ-R', program: 'S1 Teknologi Pangan' },
    { mbti: 'ENTJ-I', program: 'S1 Data Sains' },
    { mbti: 'ENTJ-I', program: 'S1 Sistem Informasi' },
    { mbti: 'ENTJ-I', program: 'S1 Rekayasa Perangkat Lunak' },
    { mbti: 'ENTJ-I', program: 'S1 Psikologi' },
    { mbti: 'ENTJ-A', program: 'S1 Desain Komunikasi Visual' },
    { mbti: 'ENTJ-A', program: 'S1 Desain Produk & Inovasi' },
    { mbti: 'ENTJ-A', program: 'S1 Film dan Animasi' },
    { mbti: 'ENTJ-A', program: 'S1 Kriya' },
    { mbti: 'ENTJ-S', program: 'S1 Psikologi' },
    { mbti: 'ENTJ-S', program: 'S1 Ilmu Komunikasi' },
    { mbti: 'ENTJ-S', program: 'S1 Digital Public Relations' },
    { mbti: 'ENTJ-S', program: 'D3 Hospitality and Culinary Art' },
    { mbti: 'ENTJ-E', program: 'S1 Administrasi Bisnis' },
    { mbti: 'ENTJ-E', program: 'S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)' },
    { mbti: 'ENTJ-E', program: 'S1 Bisnis Digital' },
    { mbti: 'ENTJ-E', program: 'S1 Smart Science and Technology' },
    { mbti: 'ENTJ-E', program: 'S1 Digital Content Broadcasting' },
    { mbti: 'ENTJ-C', program: 'S1 Akuntansi' },
    { mbti: 'ENTJ-C', program: 'D3 Sistem Informasi Akuntansi' },
    { mbti: 'ESFP-R', program: 'S1 Teknik Elektro' },
    { mbti: 'ESFP-R', program: 'S1 Teknik Komputer' },
    { mbti: 'ESFP-R', program: 'S1 Teknik Industri' },
    { mbti: 'ESFP-I', program: 'S1 Data Sains' },
    { mbti: 'ESFP-I', program: 'S1 Sistem Informasi' },
    { mbti: 'ESFP-I', program: 'S1 Rekayasa Perangkat Lunak' },
    { mbti: 'ESFP-I', program: 'S1 Psikologi' },
    { mbti: 'ESFP-A', program: 'S1 Desain Komunikasi Visual' },
    { mbti: 'ESFP-A', program: 'S1 Desain Interior' },
    { mbti: 'ESFP-A', program: 'S1 Kriya' },
    { mbti: 'ESFP-A', program: 'S1 Film dan Animasi' },
    { mbti: 'ESFP-A', program: 'S1 Creative Arts' },
    { mbti: 'ESFP-S', program: 'S1 Psikologi' },
    { mbti: 'ESFP-S', program: 'S1 Ilmu Komunikasi' },
    { mbti: 'ESFP-S', program: 'S1 Digital Public Relations' },
    { mbti: 'ESFP-S', program: 'D3 Hospitality and Culinary Art' },
    { mbti: 'ESFP-E', program: 'S1 Administrasi Bisnis' },
    { mbti: 'ESFP-E', program: 'S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)' },
    { mbti: 'ESFP-E', program: 'S1 Bisnis Digital' },
    { mbti: 'ESFP-E', program: 'S1 Digital Content Broadcasting' },
    { mbti: 'ESFP-C', program: 'S1 Akuntansi' },
    { mbti: 'ESFP-C', program: 'D3 Sistem Informasi Akuntansi' },
    { mbti: 'ESFJ-R', program: 'S1 Teknik Elektro' },
    { mbti: 'ESFJ-R', program: 'S1 Teknik Komputer' },
    { mbti: 'ESFJ-R', program: 'S1 Teknik Industri' },
    { mbti: 'ESFJ-R', program: 'S1 Teknologi Pangan' },
    { mbti: 'ESFJ-I', program: 'S1 Data Sains' },
    { mbti: 'ESFJ-I', program: 'S1 Sistem Informasi' },
    { mbti: 'ESFJ-I', program: 'S1 Rekayasa Perangkat Lunak' },
    { mbti: 'ESFJ-I', program: 'S1 Psikologi' },
    { mbti: 'ESFJ-A', program: 'S1 Desain Komunikasi Visual' },
    { mbti: 'ESFJ-A', program: 'S1 Desain Interior' },
    { mbti: 'ESFJ-A', program: 'S1 Kriya' },
    { mbti: 'ESFJ-A', program: 'S1 Film dan Animasi' },
    { mbti: 'ESFJ-A', program: 'S1 Creative Arts' },
    { mbti: 'ESFJ-S', program: 'S1 Psikologi' },
    { mbti: 'ESFJ-S', program: 'S1 Ilmu Komunikasi' },
    { mbti: 'ESFJ-S', program: 'S1 Digital Public Relations' },
    { mbti: 'ESFJ-S', program: 'D3 Hospitality and Culinary Art' },
    { mbti: 'ESFJ-E', program: 'S1 Administrasi Bisnis' },
    { mbti: 'ESFJ-E', program: 'S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)' },
    { mbti: 'ESFJ-E', program: 'S1 Bisnis Digital' },
    { mbti: 'ESFJ-E', program: 'S1 Smart Science and Technology' },
    { mbti: 'ESFJ-C', program: 'S1 Akuntansi' },
    { mbti: 'ESFJ-C', program: 'D3 Sistem Informasi Akuntansi' },
    { mbti: 'ESTP-R', program: 'S1 Teknik Elektro' },
    { mbti: "ESTP-R", program: "S1 Teknik Komputer" },
    { mbti: "ESTP-R", program: "S1 Teknik Industri" },
    { mbti: "ESTP-R", program: "S1 Teknologi Pangan" },
    { mbti: "ESTP-I", program: "S1 Data Sains" },
    { mbti: "ESTP-I", program: "S1 Sistem Informasi" },
    { mbti: "ESTP-I", program: "S1 Rekayasa Perangkat Lunak" },
    { mbti: "ESTP-I", program: "S1 Psikologi" },
    { mbti: "ESTP-A", program: "S1 Desain Komunikasi Visual" },
    { mbti: "ESTP-A", program: "S1 Kriya" },
    { mbti: "ESTP-A", program: "S1 Desain Interior" },
    { mbti: "ESTP-A", program: "S1 Film dan Animasi" },
    { mbti: "ESTP-A", program: "S1 Creative Arts" },
    { mbti: "ESTP-S", program: "S1 Psikologi" },
    { mbti: "ESTP-S", program: "S1 Ilmu Komunikasi" },
    { mbti: "ESTP-S", program: "S1 Digital Public Relations" },
    { mbti: "ESTP-S", program: "D3 Hospitality and Culinary Art" },
    { mbti: "ESTP-E", program: "S1 Administrasi Bisnis" },
    { mbti: "ESTP-E", program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)" },
    { mbti: "ESTP-E", program: "S1 Bisnis Digital" },
    { mbti: "ESTP-E", program: "S1 Smart Science and Technology" },
    { mbti: "ESTP-C", program: "S1 Akuntansi" },
    { mbti: "ESTP-C", program: "D3 Sistem Informasi Akuntansi" }
]
