import { IFormulaCarier } from "../interfaces/formula-carier.interface";

export const formulaCarierData: IFormulaCarier[] = [
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Sosial",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Administrasi Bisnis",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Sosial",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Administrasi Bisnis",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Sosial",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Administrasi Bisnis",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Sosial",
        codeSDS: "IE",
        code1: "I",
        code2: "E",
        program: "S1 Administrasi Bisnis",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Sosial",
        codeSDS: "EI",
        code1: "E",
        code2: "I",
        program: "S1 Administrasi Bisnis",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Sosial",
        codeSDS: "SE",
        code1: "S",
        code2: "E",
        program: "S1 Administrasi Bisnis",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Sosial",
        codeSDS: "ES",
        code1: "E",
        code2: "S",
        program: "S1 Administrasi Bisnis",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Akuntansi",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Akuntansi",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Akuntansi",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Akuntansi",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Bisnis Digital",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Bisnis Digital",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Bisnis Digital",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Bisnis Digital",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Desain Interior",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Desain Interior",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Desain Interior",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Desain Interior",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "AS",
        code1: "A",
        code2: "S",
        program: "S1 Desain Interior",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "SA",
        code1: "S",
        code2: "A",
        program: "S1 Desain Interior",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Desain Produk & Inovasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Desain Produk & Inovasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Desain Produk & Inovasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "IA",
        code1: "I",
        code2: "A",
        program: "S1 Desain Produk & Inovasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "AI",
        code1: "A",
        code2: "I",
        program: "S1 Desain Produk & Inovasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Film dan Animasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Film dan Animasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "AC",
        code1: "A",
        code2: "C",
        program: "S1 Film dan Animasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Film dan Animasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "AS",
        code1: "A",
        code2: "S",
        program: "S1 Film dan Animasi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Digital Public Relations",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Digital Public Relations",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "SA",
        code1: "S",
        code2: "A",
        program: "S1 Digital Public Relations",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "AS",
        code1: "A",
        code2: "S",
        program: "S1 Digital Public Relations",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "ES",
        code1: "E",
        code2: "S",
        program: "S1 Digital Public Relations",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "SE",
        code1: "S",
        code2: "E",
        program: "S1 Digital Public Relations",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Sosial",
        cluster3: "Manajemen",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Ilmu Komunikasi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Sosial",
        cluster3: "Manajemen",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Ilmu Komunikasi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Sosial",
        cluster3: "Manajemen",
        codeSDS: "SA",
        code1: "S",
        code2: "A",
        program: "S1 Ilmu Komunikasi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Sosial",
        cluster3: "Manajemen",
        codeSDS: "AS",
        code1: "A",
        code2: "S",
        program: "S1 Ilmu Komunikasi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Sosial",
        cluster3: "Manajemen",
        codeSDS: "IS",
        code1: "I",
        code2: "S",
        program: "S1 Ilmu Komunikasi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Komunikasi",
        cluster2: "Sosial",
        cluster3: "Manajemen",
        codeSDS: "SI",
        code1: "S",
        code2: "I",
        program: "S1 Ilmu Komunikasi",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Informatika",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Informatika",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Informatika",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Informatika",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Informatika",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Informatika",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Manajemen",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Kriya (Fashion and Textile Design)",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Manajemen",
        codeSDS: "AC",
        code1: "A",
        code2: "C",
        program: "S1 Kriya (Fashion and Textile Design)",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Manajemen",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Kriya (Fashion and Textile Design)",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Manajemen",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Kriya (Fashion and Textile Design)",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Manajemen",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Kriya (Fashion and Textile Design)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "IE",
        code1: "I",
        code2: "E",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "EI",
        code1: "E",
        code2: "I",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Teknologi Informasi",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Manajemen Bisnis Telekomunikasi & Informatika (MBTI)",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Leisure Management",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "SI",
        code1: "S",
        code2: "I",
        program: "S1 Leisure Management",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "IS",
        code1: "I",
        code2: "S",
        program: "S1 Leisure Management",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Leisure Management",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Leisure Management",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Leisure Management",
    },
    {
        orientation: "DATA_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Leisure Management",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "D3 Digital Marketing",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "D3 Digital Marketing",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "D3 Digital Marketing",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "CA",
        code1: "C",
        code2: "A",
        program: "D3 Digital Marketing",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "D3 Digital Marketing",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "ES",
        code1: "E",
        code2: "S",
        program: "D3 Digital Marketing",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Bisnis",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "SE",
        code1: "S",
        code2: "E",
        program: "D3 Digital Marketing",
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Manajemen Rekayasa Industri",
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Manajemen Rekayasa Industri",
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Manajemen Rekayasa Industri",
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Manajemen Rekayasa Industri",
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Manajemen Rekayasa Industri",
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Manajemen Rekayasa Industri",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Komunikasi",
        cluster2: "Desain",
        cluster3: "Teknologi Informasi",
        codeSDS: "AC",
        code1: "A",
        code2: "C",
        program: "S1 Digital Content Broadcasting",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Komunikasi",
        cluster2: "Desain",
        cluster3: "Teknologi Informasi",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Digital Content Broadcasting",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Komunikasi",
        cluster2: "Desain",
        cluster3: "Teknologi Informasi",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Digital Content Broadcasting",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Komunikasi",
        cluster2: "Desain",
        cluster3: "Teknologi Informasi",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Digital Content Broadcasting",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Komunikasi",
        cluster2: "Desain",
        cluster3: "Teknologi Informasi",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Digital Content Broadcasting",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Komunikasi",
        cluster2: "Desain",
        cluster3: "Teknologi Informasi",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Digital Content Broadcasting",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Komunikasi",
        cluster2: "Desain",
        cluster3: "Teknologi Informasi",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Digital Content Broadcasting",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "D3 Hospitality and Culinary Art",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "D3 Hospitality and Culinary Art",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "CS",
        code1: "C",
        code2: "S",
        program: "D3 Hospitality and Culinary Art",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Pariwisata",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "SE",
        code1: "S",
        code2: "E",
        program: "D3 Hospitality and Culinary Art",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "IS",
        code1: "I",
        code2: "S",
        program: "S1 Psikologi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Psikologi",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Psikologi"
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "SI",
        code1: "S",
        code2: "I",
        program: "S1 Psikologi"
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "SC",
        code1: "S",
        code2: "C",
        program: "S1 Psikologi"
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "SE",
        code1: "S",
        code2: "E",
        program: "S1 Psikologi"
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "AS",
        code1: "A",
        code2: "S",
        program: "S1 Psikologi"
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Sosial",
        cluster2: "Kesehatan",
        cluster3: "Komunikasi",
        codeSDS: "SA",
        code1: "S",
        code2: "A",
        program: "S1 Psikologi"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Rekayasa Perangkat Lunak"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "AI",
        code1: "A",
        code2: "I",
        program: "S1 Rekayasa Perangkat Lunak"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IA",
        code1: "I",
        code2: "A",
        program: "S1 Rekayasa Perangkat Lunak"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Rekayasa Perangkat Lunak"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IA",
        code1: "I",
        code2: "A",
        program: "S1 Rekayasa Perangkat Lunak"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Rekayasa Perangkat Lunak"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Rekayasa Perangkat Lunak"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Data Sains"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Data Sains"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Data Sains"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Data Sains"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Data Sains"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Data Sains"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Creative Arts (Intermedia Visual Arts)"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Creative Arts (Intermedia Visual Arts)"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Creative Arts (Intermedia Visual Arts)"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Creative Arts (Intermedia Visual Arts)"
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Seni",
        cluster2: "Desain",
        cluster3: "Komunikasi",
        codeSDS: "SA",
        code1: "S",
        code2: "A",
        program: "S1 Creative Arts (Intermedia Visual Arts)"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Komputer",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Sistem Informasi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Komputer",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Sistem Informasi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Komputer",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Sistem Informasi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Komputer",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Sistem Informasi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Komputer",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Sistem Informasi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Komputer",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Sistem Informasi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "D3 Sistem Informasi Akuntansi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "D3 Sistem Informasi Akuntansi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "D3 Sistem Informasi Akuntansi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "D3 Sistem Informasi Akuntansi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "D3 Sistem Informasi Akuntansi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Bisnis",
        cluster3: "Informasi",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "D3 Sistem Informasi Akuntansi"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "D4 Sistem Informasi Kota Cerdas"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "D4 Sistem Informasi Kota Cerdas"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "D4 Sistem Informasi Kota Cerdas"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "D4 Sistem Informasi Kota Cerdas"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "D4 Sistem Informasi Kota Cerdas"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "D4 Sistem Informasi Kota Cerdas"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Kesehatan",
        cluster3: "Komputer",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Teknik Biomedis"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Kesehatan",
        cluster3: "Komputer",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Teknik Biomedis"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Kesehatan",
        cluster3: "Komputer",
        codeSDS: "SI",
        code1: "S",
        code2: "I",
        program: "S1 Teknik Biomedis"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Kesehatan",
        cluster3: "Komputer",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Teknik Biomedis"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Kesehatan",
        cluster3: "Komputer",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Teknik Biomedis"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Kesehatan",
        cluster3: "Komputer",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Teknik Biomedis"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Teknik Elektro"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Teknik Elektro"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Teknik Elektro"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Teknik Elektro"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Teknik Elektro"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Teknik Elektro"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Teknik",
        cluster3: "Manajemen",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Smart Science and Technology"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Teknik",
        cluster3: "Manajemen",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Smart Science and Technology"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Teknik",
        cluster3: "Manajemen",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Smart Science and Technology"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Teknik",
        cluster3: "Manajemen",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Smart Science and Technology"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Teknik",
        cluster3: "Manajemen",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Smart Science and Technology"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Teknik",
        cluster3: "Manajemen",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Smart Science and Technology"
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Teknik Industri"
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Teknik Industri"
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Teknik Industri"
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Teknik Industri"
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "IE",
        code1: "I",
        code2: "E",
        program: "S1 Teknik Industri"
    },
    {
        orientation: "MANUSIA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Bisnis",
        codeSDS: "EI",
        code1: "E",
        code2: "I",
        program: "S1 Teknik Industri"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Komputer",
        cluster3: "Teknologi Informasi",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Teknik Komputer"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Komputer",
        cluster3: "Teknologi Informasi",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Teknik Komputer"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Komputer",
        cluster3: "Teknologi Informasi",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Teknik Komputer"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Komputer",
        cluster3: "Teknologi Informasi",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Teknik Komputer"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Komputer",
        cluster3: "Teknologi Informasi",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Teknik Komputer"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Komputer",
        cluster3: "Teknologi Informasi",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Teknik Komputer"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Teknologi Informasi",
        cluster3: "Bisnis",
        codeSDS: "CE",
        code1: "C",
        code2: "E",
        program: "S1 Digital Supply Chain"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Teknologi Informasi",
        cluster3: "Bisnis",
        codeSDS: "EC",
        code1: "E",
        code2: "C",
        program: "S1 Digital Supply Chain"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Teknologi Informasi",
        cluster3: "Bisnis",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Digital Supply Chain"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Teknologi Informasi",
        cluster3: "Bisnis",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Digital Supply Chain"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Teknologi Informasi",
        cluster3: "Bisnis",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Digital Supply Chain"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Teknologi Informasi",
        cluster3: "Bisnis",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Digital Supply Chain"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Manajemen",
        cluster2: "Teknologi Informasi",
        cluster3: "Bisnis",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Digital Supply Chain"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Electrical Energy Engineering"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Electrical Energy Engineering"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Electrical Energy Engineering"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Electrical Energy Engineering"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Electrical Energy Engineering"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Manajemen",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Electrical Energy Engineering"
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Teknik Telekomunikasi",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Teknik Telekomunikasi",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Teknik Telekomunikasi",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Teknik Telekomunikasi",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Teknik Telekomunikasi",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Teknologi Informasi",
        cluster3: "Komputer",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Teknik Telekomunikasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "RI",
        code1: "R",
        code2: "I",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "CR",
        code1: "C",
        code2: "R",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "RC",
        code1: "R",
        code2: "C",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "IDE_TEKNOLOGI",
        cluster1: "Teknologi Informasi",
        cluster2: "Komputer",
        cluster3: "Manajemen",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Teknologi Informasi",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Teknologi Pangan",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "CI",
        code1: "C",
        code2: "I",
        program: "S1 Teknologi Pangan",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "IS",
        code1: "I",
        code2: "S",
        program: "S1 Teknologi Pangan",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "SI",
        code1: "S",
        code2: "I",
        program: "S1 Teknologi Pangan",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "ER",
        code1: "E",
        code2: "R",
        program: "S1 Teknologi Pangan",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Teknik",
        cluster2: "Manajemen",
        cluster3: "Sosial",
        codeSDS: "RE",
        code1: "R",
        code2: "E",
        program: "S1 Teknologi Pangan",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Seni",
        codeSDS: "AI",
        code1: "A",
        code2: "I",
        program: "S1 Terapan Digital Creative Multimedia (DCM)",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Seni",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Terapan Digital Creative Multimedia (DCM)",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Seni",
        codeSDS: "AC",
        code1: "A",
        code2: "C",
        program: "S1 Terapan Digital Creative Multimedia (DCM)",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Seni",
        codeSDS: "IA",
        code1: "I",
        code2: "A",
        program: "S1 Terapan Digital Creative Multimedia (DCM)",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Seni",
        codeSDS: "IC",
        code1: "I",
        code2: "C",
        program: "S1 Terapan Digital Creative Multimedia (DCM)",
    },
    {
        orientation: "DATA_TEKNOLOGI",
        cluster1: "Desain",
        cluster2: "Teknologi Informasi",
        cluster3: "Seni",
        codeSDS: "IR",
        code1: "I",
        code2: "R",
        program: "S1 Terapan Digital Creative Multimedia (DCM)",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "AR",
        code1: "A",
        code2: "R",
        program: "S1 Desain Komunikasi Visual",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "AE",
        code1: "A",
        code2: "E",
        program: "S1 Desain Komunikasi Visual",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "EA",
        code1: "E",
        code2: "A",
        program: "S1 Desain Komunikasi Visual",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "RA",
        code1: "R",
        code2: "A",
        program: "S1 Desain Komunikasi Visual",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "AS",
        code1: "A",
        code2: "S",
        program: "S1 Desain Komunikasi Visual",
    },
    {
        orientation: "IDE_MANUSIA",
        cluster1: "Desain",
        cluster2: "Seni",
        cluster3: "Komunikasi",
        codeSDS: "SA",
        code1: "S",
        code2: "A",
        program: "S1 Desain Komunikasi Visual",
    }
]