import { IMajor } from "../interfaces/major.interface";

export const majorData: IMajor[] = [
    { name: "Akuntansi", url: "", degree: "S1", code: "S1-AK" },
    { name: "Data Sains", url: "", degree: "S1", code: "S1-DS" },
    { name: "Digital Marketing", url: "", degree: "D3", code: "D3-DM" },
    { name: "Digital Supply Chain", url: "", degree: "S1", code: "S1-DSC" },
    { name: "Sistem Informasi", url: "", degree: "S1", code: "S1-SI" },
    { name: "Sistem Informasi Akuntansi", url: "", degree: "D3", code: "D3-SIA" },
    { name: "Sistem Informasi Kota Cerdas", url: "", degree: "D4", code: "D4-SIKC" },
    { name: "Smart Science and Technology", url: "", degree: "S1", code: "S1-SST" },
    { name: "Administrasi Bisnis", url: "", degree: "S1", code: "S1-AB" },
    { name: "Manajemen Bisnis Telekomunikasi & Informatika (MBTI)", url: "", degree: "S1", code: "S1-MBTI" },
    { name: "Leisure Management", url: "", degree: "S1", code: "S1-LM" },
    { name: "Bisnis Digital", url: "", degree: "S1", code: "S1-BD" },
    { name: "Informatika", url: "", degree: "S1", code: "S1-INF" },
    { name: "Terapan Digital Creative Multimedia (DCM)", url: "", degree: "S1", code: "S1-DCM" },
    { name: "Digital Content Broadcasting", url: "", degree: "S1", code: "S1-DCB" },
    { name: "Ilmu Komunikasi", url: "", degree: "S1", code: "S1-IK" },
    { name: "Digital Public Relations", url: "", degree: "S1", code: "S1-DPR" },
    { name: "Psikologi", url: "", degree: "S1", code: "S1-PS" },
    { name: "Desain Interior", url: "", degree: "S1", code: "S1-DI" },
    { name: "Desain Komunikasi Visual", url: "", degree: "S1", code: "S1-DKV" },
    { name: "Kriya (Fashion and Textile Design)", url: "", degree: "S1", code: "S1-K" },
    { name: "Hospitality and Culinary Art", url: "", degree: "D3", code: "D3-HCA" },
    { name: "Manajemen Rekayasa Industri", url: "", degree: "S1", code: "S1-MRI" },
    { name: "Teknik Industri", url: "", degree: "S1", code: "S1-TI" },
    { name: "Rekayasa Perangkat Lunak", url: "", degree: "S1", code: "S1-RPL" },
    { name: "Creative Arts (Intermedia Visual Arts)", url: "", degree: "S1", code: "S1-CA" },
    { name: "Teknologi Informasi", url: "", degree: "S1", code: "S1-IT" },
    { name: "Desain Produk & Inovasi", url: "", degree: "S1", code: "S1-DPI" },
    { name: "Film dan Animasi", url: "", degree: "S1", code: "S1-FA" },
    { name: "Teknik Biomedis", url: "", degree: "S1", code: "S1-TB" },
    { name: "Teknik Elektro", url: "", degree: "S1", code: "S1-TE" },
    { name: "Teknik Komputer", url: "", degree: "S1", code: "S1-TK" },
    { name: "Teknologi Pangan", url: "", degree: "S1", code: "S1-TP" },
    { name: "Teknik Telekomunikasi", url: "", degree: "S1", code: "S1-TT" },
    { name: "Electrical Energy Engineering", url: "", degree: "S1", code: "S1-EEE" }
];
