export interface IMbti {
    codeMbti: string;
    naration: string;
}

const mbtiData: IMbti[] = [
    {
        codeMbti: "ENTJ-R",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu adalah seorang pemimpin yang berani, cerdas, dan berorientasi pada tujuan. Kamu memiliki potensi untuk mencapai posisi kepemimpinan di berbagai bidang. Di dunia kerja modern yang terstruktur, kemampuanmu untuk berpikir strategis dan efisien akan sangat dihargai. Meskipun terkadang kamu perlu belajar menyeimbangkan fokusmu pada tujuan besar dengan memperhatikan detail, Telkom University akan membantumu mengasah kemampuan tersebut.\n\nDi Telkom University, kamu akan belajar untuk berpikir sistematis, mengembangkan kemampuan analitis, dan mengelola berbagai proyek secara efisien. Kamu akan mempelajari keterampilan kepemimpinan dan manajemen yang akan membantumu memimpin tim dan mencapai tujuan dengan efektif. Meskipun karier yang sangat teknis mungkin bukan prioritas utamamu, kamu akan belajar untuk menghargai pentingnya detail dan ketelitian dalam berbagai bidang. Telkom University akan memberimu kesempatan untuk mengembangkan visi dan strategi jangka panjang, sambil tetap mampu beradaptasi dengan perubahan dan tantangan di dunia kerja modern. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses pembelajaran di Telkom University akan memberimu kesempatan untuk berkembang dan mencapai potensi terbaikmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENTJ-I",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu adalah seorang pemimpin yang berani, cerdas, dan berorientasi pada tujuan. Kamu memiliki potensi untuk mencapai posisi kepemimpinan di berbagai bidang, dan memiliki visi yang kuat serta kemampuan untuk mensintesis informasi dan membuat keputusan dengan tepat. Di Telkom University, kamu akan belajar untuk mengembangkan kemampuan kepemimpinan dan manajemenmu secara maksimal.\n\nDi Telkom University, kamu akan belajar untuk berpikir strategis dan efisien, mengembangkan kemampuan analitis, dan mengelola berbagai proyek secara efektif. Kamu akan mempelajari keterampilan kepemimpinan dan manajemen yang akan membantumu memimpin tim dan mencapai tujuan dengan tepat. Kamu akan belajar untuk menyeimbangkan visi jangka panjang dengan perhatian pada detail dan eksekusi yang efektif. Meskipun pekerjaan yang membutuhkan penelitian intensif di laboratorium mungkin bukan yang paling sesuai untukmu, kamu akan belajar bagaimana mengaplikasikan kemampuan analitis dan strategis dalam berbagai bidang, termasuk riset dan pengembangan teknologi, manajemen proyek, atau bahkan kewirausahaan. Telkom University akan memberimu kesempatan untuk mengembangkan potensi kepemimpinan dan visi inovatifmu. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses pembelajaran di Telkom University akan memberimu kesempatan untuk berkembang dan mencapai potensi terbaikmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENTJ-A",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu adalah seorang pemimpin yang berani, cerdas, dan berorientasi pada tujuan. Kamu memiliki potensi untuk mencapai posisi kepemimpinan di berbagai bidang, dan memiliki visi yang kuat serta kemampuan untuk mensintesis informasi dan membuat keputusan dengan tepat. Di Telkom University, kamu akan belajar untuk mengembangkan kemampuan kepemimpinan dan manajemenmu secara maksimal, serta mengasah kemampuan analitis dan strategis yang kamu miliki.\n\nDi Telkom University, kamu akan belajar untuk berpikir sistematis, mengembangkan kemampuan analitis, dan mengelola berbagai proyek secara efisien. Kamu akan mempelajari keterampilan kepemimpinan dan manajemen yang akan membantumu memimpin tim dan mencapai tujuan dengan efektif. Kamu akan belajar untuk menyeimbangkan visi jangka panjang dengan perhatian pada detail dan eksekusi yang efektif. Meskipun seni dan kreativitas mungkin bukan fokus utamamu, kamu akan belajar bagaimana mengaplikasikan kemampuan berpikir strategis dan analitis untuk memecahkan masalah dan mencapai tujuan, bahkan dalam konteks yang membutuhkan kreativitas dan inovasi. Telkom University akan memberimu kesempatan untuk mengembangkan potensi kepemimpinan dan visi inovatifmu. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses pembelajaran di Telkom University akan memberimu kesempatan untuk berkembang dan mencapai potensi terbaikmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENTJ-S",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu adalah seorang pemimpin yang berani, cerdas, dan berorientasi pada tujuan. Kamu memiliki potensi untuk mencapai posisi kepemimpinan di berbagai bidang, dan memiliki visi yang kuat serta kemampuan untuk mensintesis informasi dan membuat keputusan dengan tepat. Di Telkom University, kamu akan belajar untuk mengembangkan kemampuan kepemimpinan dan manajemenmu secara maksimal, serta mengasah kemampuan analitis dan strategis yang kamu miliki.\n\nDi Telkom University, kamu akan belajar untuk berpikir sistematis, mengembangkan kemampuan analitis, dan mengelola berbagai proyek secara efisien. Kamu akan mempelajari keterampilan kepemimpinan dan manajemen yang akan membantumu memimpin tim dan mencapai tujuan dengan efektif. Kamu akan belajar untuk menyeimbangkan visi jangka panjang dengan perhatian pada detail dan eksekusi yang efektif. Meskipun pekerjaan yang terlalu berfokus pada interaksi emosional mungkin bukan yang paling sesuai, kamu akan belajar bagaimana mengaplikasikan kemampuanmu untuk memimpin dan memotivasi orang lain, serta membangun hubungan kerja yang produktif. Telkom University akan memberimu kesempatan untuk mengembangkan potensi kepemimpinan dan visi inovatifmu, sambil tetap mempertimbangkan pentingnya kolaborasi dan kerja tim. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses pembelajaran di Telkom University akan memberimu kesempatan untuk berkembang dan mencapai potensi terbaikmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENTJ-E",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu adalah seorang pemimpin yang berani, cerdas, dan berorientasi pada tujuan. Kamu memiliki potensi untuk mencapai posisi kepemimpinan di berbagai bidang, dan memiliki visi yang kuat serta kemampuan untuk mensintesis informasi dan membuat keputusan dengan tepat. Di Telkom University, kamu akan belajar untuk mengembangkan kemampuan kepemimpinan dan manajemenmu secara maksimal, serta mengasah kemampuan analitis dan strategis yang kamu miliki.\n\nDi Telkom University, kamu akan belajar untuk berpikir sistematis, mengembangkan kemampuan analitis, dan mengelola berbagai proyek secara efisien. Kamu akan mempelajari keterampilan kepemimpinan dan manajemen yang akan membantumu memimpin tim dan mencapai tujuan dengan efektif. Kamu akan belajar untuk menyeimbangkan visi jangka panjang dengan perhatian pada detail dan eksekusi yang efektif. Kemampuanmu sebagai pemimpin yang berorientasi pada hasil akan sangat berguna dalam dunia kerja modern, dan Telkom University akan memberimu kesempatan untuk mengembangkan potensi kepemimpinan dan visi inovatifmu, khususnya di bidang bisnis dan manajemen. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses pembelajaran di Telkom University akan memberimu kesempatan untuk berkembang dan mencapai potensi terbaikmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENTJ-C",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu adalah seorang pemimpin yang berani, cerdas, dan berorientasi pada tujuan. Kamu memiliki potensi untuk mencapai posisi kepemimpinan di berbagai bidang, dan memiliki visi yang kuat serta kemampuan untuk mensintesis informasi dan membuat keputusan dengan tepat. Di Telkom University, kamu akan belajar untuk mengembangkan kemampuan kepemimpinan dan manajemenmu secara maksimal, serta mengasah kemampuan analitis dan strategis yang kamu miliki.\n\nDi Telkom University, kamu akan belajar untuk berpikir sistematis, mengembangkan kemampuan analitis, dan mengelola berbagai proyek secara efisien. Kamu akan mempelajari keterampilan kepemimpinan dan manajemen yang akan membantumu memimpin tim dan mencapai tujuan dengan efektif. Kamu akan belajar untuk menyeimbangkan visi jangka panjang dengan perhatian pada detail dan eksekusi yang efektif. Kemampuanmu untuk mengelola dan menganalisis data akan sangat berguna, dan kamu akan belajar bagaimana mengaplikasikan kemampuan ini untuk mencapai tujuan-tujuan besar. Telkom University akan memberimu kesempatan untuk mengembangkan potensi kepemimpinan dan visi inovatifmu. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses pembelajaran di Telkom University akan memberimu kesempatan untuk berkembang dan mencapai potensi terbaikmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ESFP-R",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu memiliki bakat luar biasa dalam hal pekerjaan yang praktis dan langsung terlihat hasilnya. Kamu juga memiliki kepedulian sosial yang tinggi dan selera estetika yang bagus. Meskipun memilih jurusan kuliah dan karier mungkin terasa sulit, Telkom University menawarkan berbagai program studi yang akan membantumu mengasah kemampuan dan minatmu.\n\nDi Telkom University, kamu akan menemukan berbagai kesempatan untuk belajar sambil melakukan kegiatan yang praktis dan menantang. Kamu bisa mengeksplorasi berbagai bidang studi yang memungkinkanmu untuk menerapkan kemampuan praktis dan kreativitasmu. Baik itu melalui proyek-proyek yang membutuhkan keterampilan teknis, magang di perusahaan, atau kegiatan ekstrakurikuler, kamu akan menemukan cara untuk menggabungkan minatmu dengan pembelajaran akademis. Kepekaanmu terhadap isu sosial dan kemampuanmu dalam hal estetika juga bisa diasah dan diintegrasikan dengan bidang studi yang kamu pilih. Telkom University akan memberimu kesempatan untuk mengembangkan bakat dan minatmu di bidang yang kamu sukai, sekaligus memberikanmu kesempatan untuk berkontribusi bagi masyarakat. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University menyediakan lingkungan belajar yang dinamis dan mendukung, yang akan membantumu menemukan passion dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ESFP-I",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu memiliki kemampuan luar biasa dalam hal pekerjaan yang praktis dan langsung terlihat hasilnya. Kamu juga memiliki selera seni yang tinggi dan peduli terhadap sesama. Meskipun memilih jurusan kuliah dan karier mungkin terasa sulit, Telkom University menawarkan berbagai program studi yang akan membantumu mengasah kemampuan dan minatmu.\n\nDi Telkom University, kamu akan menemukan berbagai kesempatan untuk belajar sambil melakukan kegiatan yang praktis dan menantang. Kamu bisa mengeksplorasi berbagai bidang studi yang memungkinkanmu untuk menerapkan kemampuan praktis dan kreativitasmu. Baik itu melalui proyek-proyek yang membutuhkan keterampilan teknis, magang di perusahaan, atau kegiatan ekstrakurikuler, kamu akan menemukan cara untuk menggabungkan minatmu dengan pembelajaran akademis. Kepekaanmu terhadap isu sosial dan kemampuanmu dalam hal estetika juga bisa diasah dan diintegrasikan dengan bidang studi yang kamu pilih. Di Telkom University, kamu juga akan belajar untuk berpikir analitis dan sistematis, yang akan membantumu dalam memecahkan masalah dan membuat keputusan yang tepat, terutama jika kamu tertarik pada bidang studi yang membutuhkan keterampilan analitis yang kuat. Telkom University akan memberimu kesempatan untuk mengembangkan bakat dan minatmu di bidang yang kamu sukai, sekaligus memberimu kesempatan untuk berkontribusi bagi masyarakat. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University menyediakan lingkungan belajar yang dinamis dan mendukung, yang akan membantumu menemukan passion dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ESFP-A",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu memiliki kemampuan luar biasa dalam hal pekerjaan yang praktis dan langsung terlihat hasilnya. Kamu juga memiliki selera seni yang tinggi dan peduli terhadap sesama. Meskipun memilih jurusan kuliah dan karier mungkin terasa sulit, Telkom University menawarkan berbagai program studi yang akan membantumu mengasah kemampuan dan minatmu.\n\nDi Telkom University, kamu akan menemukan berbagai kesempatan untuk belajar sambil melakukan kegiatan yang praktis dan menantang. Kamu bisa mengeksplorasi berbagai bidang studi yang memungkinkanmu untuk menerapkan kemampuan praktis dan kreativitasmu. Baik itu melalui proyek-proyek yang membutuhkan keterampilan teknis, magang di perusahaan, atau kegiatan ekstrakurikuler, kamu akan menemukan cara untuk menggabungkan minatmu dengan pembelajaran akademis. Kepekaanmu terhadap keindahan dan kepedulianmu terhadap sesama juga bisa diasah dan diintegrasikan dengan bidang studi yang kamu pilih. Telkom University akan memberimu kesempatan untuk mengembangkan bakat dan minatmu di bidang yang kamu sukai, sekaligus memberimu kesempatan untuk berkontribusi bagi masyarakat. Di kampus ini, kamu juga akan belajar bagaimana mengkombinasikan bakatmu dalam hal estetika dan kreativitas dengan kemampuan praktis untuk menciptakan karya yang inovatif dan berdampak positif. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University menyediakan lingkungan belajar yang dinamis dan mendukung, yang akan membantumu menemukan passion dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ESFP-S",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu memiliki kemampuan luar biasa dalam hal pekerjaan yang praktis dan langsung terlihat hasilnya. Kamu juga memiliki selera seni yang tinggi dan peduli terhadap sesama. Meskipun memilih jurusan kuliah dan karier mungkin terasa sulit, Telkom University menawarkan berbagai program studi yang akan membantumu mengasah kemampuan dan minatmu.\n\nDi Telkom University, kamu akan menemukan berbagai kesempatan untuk belajar sambil melakukan kegiatan yang praktis dan menantang. Kamu bisa mengeksplorasi berbagai bidang studi yang memungkinkanmu untuk menerapkan kemampuan praktis dan kreativitasmu. Baik itu melalui proyek-proyek yang membutuhkan keterampilan teknis, magang di perusahaan, atau kegiatan ekstrakurikuler, kamu akan menemukan cara untuk menggabungkan minatmu dengan pembelajaran akademis. Kepekaanmu terhadap isu sosial dan kemampuanmu dalam hal estetika juga bisa diasah dan diintegrasikan dengan bidang studi yang kamu pilih. Di Telkom University, kamu juga akan belajar bagaimana mengelola berbagai tantangan yang mungkin muncul dan menemukan cara untuk menyeimbangkan keinginanmu untuk terlibat dalam pekerjaan yang menarik dan menantang dengan kepedulianmu terhadap sesama. Telkom University akan memberimu kesempatan untuk mengembangkan bakat dan minatmu di bidang yang kamu sukai, sekaligus memberimu kesempatan untuk berkontribusi bagi masyarakat, baik melalui jalur profesi maupun kegiatan sosial. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University menyediakan lingkungan belajar yang dinamis dan mendukung, yang akan membantumu menemukan passion dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ESFP-E",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu memiliki kemampuan luar biasa dalam hal pekerjaan yang praktis dan langsung terlihat hasilnya. Kamu juga memiliki selera seni yang tinggi dan peduli terhadap sesama. Meskipun memilih jurusan kuliah dan karier mungkin terasa sulit, Telkom University menawarkan berbagai program studi yang akan membantumu mengasah kemampuan dan minatmu.\n\nDi Telkom University, kamu akan menemukan berbagai kesempatan untuk belajar sambil melakukan kegiatan yang praktis dan menantang. Kamu bisa mengeksplorasi berbagai bidang studi yang memungkinkanmu untuk menerapkan kemampuan praktis dan kreativitasmu. Baik itu melalui proyek-proyek yang membutuhkan keterampilan teknis, magang di perusahaan, atau kegiatan ekstrakurikuler, kamu akan menemukan cara untuk menggabungkan minatmu dengan pembelajaran akademis. Kepekaanmu terhadap isu sosial dan kemampuanmu dalam hal estetika juga bisa diasah dan diintegrasikan dengan bidang studi yang kamu pilih. Di Telkom University, kamu juga akan belajar untuk mengembangkan kemampuanmu dalam hal komunikasi, presentasi, dan negosiasi, yang akan sangat berguna dalam berbagai jalur karier. Meskipun karier di bidang bisnis dan manajemen mungkin bukan yang paling sesuai untukmu, keterampilan yang kamu pelajari di Telkom University akan memberimu fleksibilitas untuk mengejar berbagai peluang karier, baik yang berfokus pada aspek praktis maupun yang membutuhkan kreativitas dan interaksi sosial. Telkom University akan memberimu kesempatan untuk mengembangkan bakat dan minatmu di bidang yang kamu sukai, sekaligus memberimu kesempatan untuk berkontribusi bagi masyarakat. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University menyediakan lingkungan belajar yang dinamis dan mendukung, yang akan membantumu menemukan passion dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ESFP-C",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu punya bakat luar biasa dalam hal pekerjaan yang praktis dan langsung terlihat hasilnya. Kamu juga memiliki selera seni yang tinggi dan peduli terhadap sesama. Meskipun memilih jurusan kuliah dan karier mungkin terasa sulit, Telkom University menawarkan berbagai program studi yang akan membantumu mengasah kemampuan dan minatmu.\n\nDi Telkom University, kamu akan menemukan berbagai kesempatan untuk belajar sambil melakukan kegiatan yang praktis dan menantang. Kamu bisa mengeksplorasi berbagai bidang studi yang memungkinkanmu untuk menerapkan kemampuan praktis dan kreativitasmu. Baik itu melalui proyek-proyek yang membutuhkan keterampilan teknis, magang di perusahaan, atau kegiatan ekstrakurikuler, kamu akan menemukan cara untuk menggabungkan minatmu dengan pembelajaran akademis. Kepekaanmu terhadap isu sosial dan kemampuanmu dalam hal estetika juga bisa diasah dan diintegrasikan dengan bidang studi yang kamu pilih. Di Telkom University, kamu juga akan belajar keterampilan organisasi dan manajemen yang baik. Meskipun pekerjaan yang sangat administratif mungkin bukan yang paling sesuai untukmu, keterampilan ini akan sangat berharga dalam mengelola proyek-proyek dan mencapai tujuan secara efektif. Telkom University akan memberimu kesempatan untuk mengembangkan bakat dan minatmu di bidang yang kamu sukai, sekaligus memberimu kesempatan untuk berkontribusi bagi masyarakat. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University menyediakan lingkungan belajar yang dinamis dan mendukung, yang akan membantumu menemukan passion dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ESFJ-R",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu memiliki kemampuan luar biasa dalam berinteraksi dengan orang lain dan senang membantu mereka. Kamu juga memiliki perhatian terhadap detail dan keinginan untuk melestarikan hal-hal yang berharga. Meskipun memilih jurusan kuliah dan karier mungkin terasa sulit, Telkom University menawarkan berbagai program studi yang akan membantumu mengasah kemampuan dan minatmu.\n\nDi Telkom University, kamu akan menemukan berbagai kesempatan untuk belajar sambil melakukan kegiatan yang menantang dan bermanfaat bagi orang lain. Kamu bisa mengeksplorasi berbagai bidang studi yang memungkinkanmu untuk menerapkan kemampuan interpersonal dan kreativitasmu. Baik itu melalui proyek-proyek kelompok, kegiatan sosial, atau magang di perusahaan, kamu akan menemukan cara untuk menggabungkan minatmu dengan pembelajaran akademis. Meskipun pekerjaan yang sangat menekankan keterampilan fisik mungkin bukan yang paling sesuai untukmu, kamu akan belajar untuk mengelola waktu dan sumber daya secara efektif, mengembangkan kemampuan organisasi dan manajemen yang baik, dan mengasah kemampuan komunikasi dan presentasimu. Di Telkom University, kamu akan belajar untuk menggabungkan kemampuan interpersonalmu dengan keterampilan praktis untuk mencapai tujuan bersama. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University menyediakan lingkungan belajar yang dinamis dan mendukung, yang akan membantumu menemukan passion dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ESFJ-I",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu memiliki kemampuan luar biasa dalam berinteraksi dengan orang lain dan senang membantu mereka mencapai potensi terbaiknya. Kamu juga kreatif dan berorientasi pada tujuan, serta memiliki semangat untuk berkontribusi dan membuat perbedaan positif. Meskipun dunia kerja modern mungkin terkadang terasa kurang sesuai dengan pendekatanmu yang lebih humanis, Telkom University akan membantumu menemukan cara untuk menggabungkan minatmu dengan dunia profesional yang dinamis.\n\nDi Telkom University, kamu akan belajar bagaimana mengaplikasikan kemampuanmu di berbagai bidang, baik yang berhubungan langsung dengan interaksi sosial maupun yang membutuhkan analisis dan pemecahan masalah. Meskipun pekerjaan yang sangat menekankan aspek teknis dan ilmiah mungkin bukan yang paling cocok untukmu, kamu akan belajar keterampilan manajemen, kepemimpinan, dan kerja sama tim yang sangat berharga. Kamu akan mempelajari bagaimana menggabungkan kemampuanmu dalam memahami orang lain dengan kemampuan analitis untuk memecahkan masalah kompleks dan memberikan solusi inovatif. Telkom University menyediakan beragam program studi yang akan membantumu menemukan jalur karier yang sesuai dengan nilai-nilai dan passion-mu. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses pembelajaran di Telkom University akan memberimu kesempatan untuk mengembangkan potensimu secara maksimal, menemukan cara untuk menggabungkan minatmu pada interaksi sosial dengan kemampuan analisis.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ESFJ-A",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu adalah pribadi yang ramah dan peduli terhadap orang lain, serta memiliki perhatian terhadap detail dan ketelitian. Meskipun memilih jurusan kuliah dan karier mungkin terasa sulit, Telkom University menawarkan berbagai program studi yang akan membantumu mengasah kemampuan dan minatmu.\n\nDi Telkom University, kamu akan menemukan berbagai kesempatan untuk belajar sambil berinteraksi dengan orang lain dan mengembangkan kemampuanmu dalam membantu dan membimbing mereka. Kamu bisa mengeksplorasi berbagai bidang studi yang memungkinkanmu untuk menerapkan kemampuan interpersonal dan keterampilanmu dalam mengelola detail. Baik itu melalui proyek-proyek kelompok, kegiatan sosial, atau magang di perusahaan, kamu akan menemukan cara untuk menggabungkan minatmu dengan pembelajaran akademis. Di Telkom University, kamu juga akan belajar untuk mengembangkan kreativitas dan inovasi. Meskipun karier di bidang seni murni mungkin bukan yang paling sesuai untukmu, kamu akan belajar bagaimana mengaplikasikan kreativitasmu dalam berbagai bidang, misalnya dengan merancang solusi inovatif, membuat presentasi yang menarik, atau mengembangkan materi pembelajaran yang kreatif dan efektif. Telkom University akan memberimu kesempatan untuk mengembangkan bakat dan minatmu di bidang yang kamu sukai, sekaligus memberimu kesempatan untuk berkontribusi bagi masyarakat. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University menyediakan lingkungan belajar yang dinamis dan mendukung, yang akan membantumu menemukan passion dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ESFJ-S",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu memiliki kemampuan luar biasa dalam berinteraksi dengan orang lain dan senang membantu mereka. Kamu juga memiliki perhatian terhadap detail dan keinginan untuk melestarikan hal-hal yang berharga. Meskipun memilih jurusan kuliah dan karier mungkin terasa sulit, Telkom University menawarkan berbagai program studi yang akan membantumu mengasah kemampuan dan minatmu.\n\nDi Telkom University, kamu akan menemukan berbagai kesempatan untuk belajar sambil melakukan kegiatan yang bermanfaat bagi orang lain. Kamu bisa mengeksplorasi berbagai bidang studi yang memungkinkanmu untuk menerapkan kemampuan interpersonal dan kreativitasmu. Baik itu melalui proyek-proyek kelompok, kegiatan sosial, atau magang di perusahaan, kamu akan menemukan cara untuk menggabungkan minatmu dengan pembelajaran akademis. Di Telkom University, kamu akan belajar untuk mengelola waktu dan sumber daya secara efektif, mengembangkan kemampuan organisasi dan manajemen yang baik, dan mengasah kemampuan komunikasi dan presentasimu. Kamu juga akan belajar bagaimana mengaplikasikan kemampuanmu untuk memahami orang lain dan membantu mereka berkembang. Meskipun pekerjaan yang sangat menekankan riset dan analisa mungkin awalnya terasa kurang sesuai untukmu, kamu akan belajar untuk berkolaborasi dengan efektif dan mengembangkan kemampuan kepemimpinan. Telkom University akan memberimu kesempatan untuk mengembangkan bakat dan minatmu di bidang yang kamu sukai, sekaligus memberimu kesempatan untuk berkontribusi bagi masyarakat. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University menyediakan lingkungan belajar yang dinamis dan mendukung, yang akan membantumu menemukan passion dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ESFJ-E",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu adalah pribadi yang ramah dan peduli terhadap orang lain, serta memiliki perhatian terhadap detail dan keinginan untuk melestarikan hal-hal yang berharga. Meskipun memilih jurusan kuliah dan karier mungkin terasa sulit, Telkom University menawarkan berbagai program studi yang akan membantumu mengasah kemampuan dan minatmu.\n\nDi Telkom University, kamu akan menemukan berbagai kesempatan untuk belajar sambil berinteraksi dengan orang lain dan mengembangkan kemampuanmu dalam membantu dan membimbing mereka. Kamu bisa mengeksplorasi berbagai bidang studi yang memungkinkanmu untuk menerapkan kemampuan interpersonal dan keterampilanmu dalam mengelola detail. Baik itu melalui proyek-proyek kelompok, kegiatan sosial, atau magang di perusahaan, kamu akan menemukan cara untuk menggabungkan minatmu dengan pembelajaran akademis. Di Telkom University, kamu akan belajar untuk mengelola waktu dan sumber daya secara efektif, mengembangkan kemampuan organisasi dan manajemen yang baik, dan mengasah kemampuan komunikasi dan presentasimu. Meskipun pekerjaan yang membutuhkan presentasi dan persuasi mungkin awalnya terasa kurang sesuai untukmu, kamu akan belajar untuk berkomunikasi secara efektif dan membangun hubungan yang baik dengan orang lain. Kamu juga akan belajar bagaimana menyesuaikan gaya komunikasimu agar efektif dalam berbagai situasi. Telkom University akan memberimu kesempatan untuk mengembangkan bakat dan minatmu di bidang yang kamu sukai, sekaligus memberimu kesempatan untuk berkontribusi bagi masyarakat. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University menyediakan lingkungan belajar yang dinamis dan mendukung, yang akan membantumu menemukan passion dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ESFJ-C",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu adalah pribadi yang ramah dan peduli terhadap orang lain, memiliki perhatian terhadap detail, dan senang membantu orang lain berkembang. Meskipun memilih jurusan kuliah dan karier mungkin terasa sulit, Telkom University menawarkan berbagai program studi yang akan membantumu mengasah kemampuan dan minatmu.\n\nDi Telkom University, kamu akan menemukan berbagai kesempatan untuk belajar sambil berinteraksi dengan orang lain dan mengembangkan kemampuanmu dalam membantu dan membimbing mereka. Kamu bisa mengeksplorasi berbagai bidang studi yang memungkinkanmu untuk menerapkan kemampuan interpersonal dan keterampilanmu dalam mengelola detail. Baik itu melalui proyek-proyek kelompok, kegiatan sosial, atau magang di perusahaan, kamu akan menemukan cara untuk menggabungkan minatmu dengan pembelajaran akademis. Di Telkom University, kamu akan belajar untuk mengelola waktu dan sumber daya secara efektif, mengembangkan kemampuan organisasi dan manajemen yang baik, dan mengasah kemampuan komunikasi dan presentasimu. Meskipun pekerjaan yang sangat administratif mungkin awalnya terasa kurang sesuai untukmu, keterampilan organisasi dan manajemen yang kamu pelajari akan sangat berharga, tidak hanya dalam konteks pekerjaan yang lebih struktural, tetapi juga dalam mengelola proyek-proyek dan mencapai tujuan secara efektif. Telkom University akan memberimu kesempatan untuk mengembangkan bakat dan minatmu di bidang yang kamu sukai, sekaligus memberimu kesempatan untuk berkontribusi bagi masyarakat. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University menyediakan lingkungan belajar yang dinamis dan mendukung, yang akan membantumu menemukan passion dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENFP-R",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu cerdas, kreatif, dan serba bisa, punya kemampuan berinteraksi sosial yang baik, serta bakat alami dalam berwirausaha dan memimpin. Kamu juga memiliki semangat yang besar untuk menemukan jalur karier yang sesuai dengan minat dan passion-mu. Memilih karier yang biasa-biasa saja bukanlah pilihanmu; kamu lebih memilih menjalani hidup sederhana dengan melakukan hal yang kamu sukai daripada mengejar kekayaan dari pekerjaan yang tak membahagiakan.\n\nDi Telkom University, kamu akan menemukan beragam bidang studi yang bisa mengakomodasi ketertarikan dan kemampuanmu yang luas. Meskipun awalnya mungkin terasa menantang untuk menentukan jurusan yang tepat, pengalaman belajar di sini akan membantumu mengeksplorasi berbagai pilihan dan menemukan passion terdalammu. Proses pembelajaran yang interaktif dan kesempatan untuk berkolaborasi akan membantumu mengembangkan kreativitas dan kemampuan kepemimpinan. Meskipun minat terhadap pekerjaan yang bersifat praktis dan langsung berhubungan dengan benda mungkin bukan prioritas utamamu, kamu akan menemukan cara untuk menggabungkan minatmu dengan elemen-elemen praktis dalam berbagai bidang studi di Telkom University. Misalnya, kamu bisa mengaplikasikan kreativitasmu dalam proyek-proyek yang membutuhkan keahlian teknis, atau menggabungkan minat artistikmu dengan aspek teknis dalam bidang tertentu. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENFP-I",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu cerdas, kreatif, dan serba bisa, punya kemampuan komunikasi yang sangat baik, dan bakat alami dalam berwirausaha serta kepemimpinan. Kamu juga bersemangat untuk menemukan karier yang sesuai passion-mu, dan tak akan puas dengan pilihan karier yang biasa-biasa saja. Keuangan bukanlah hal utama; kamu lebih memilih hidup sederhana selagi melakukan hal yang kamu sukai.\n\nDi Telkom University, kamu akan menemukan beragam program studi yang bisa mengakomodasi minatmu yang luas. Meskipun awalnya mungkin terasa sulit menentukan jurusan yang tepat karena ketertarikanmu yang beragam, proses pembelajaran di sini akan membantumu mengeksplorasi berbagai pilihan dan menemukan passion terdalammu. Meskipun kamu mungkin awalnya lebih tertarik pada ilmu-ilmu sosial dan humaniora, Telkom University juga menawarkan berbagai program studi di bidang teknologi dan sains yang memungkinkanmu untuk mengembangkan kemampuan analitis dan pemecahan masalah. Kamu bisa menggabungkan kreativitas dan kemampuan komunikasi dengan keterampilan analisis data dan teknologi untuk menciptakan inovasi yang luar biasa. Misalnya, kamu bisa menggunakan kemampuanmu untuk memecahkan masalah sosial dengan pendekatan teknologi, atau mengembangkan riset-riset inovatif di berbagai bidang. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses pembelajaran di Telkom University akan membantumu menemukan passion terdalammu dan mengembangkan potensimu secara maksimal. Di sini, kamu akan dibekali dengan kemampuan dan pengalaman yang dibutuhkan untuk meraih karier yang sukses dan membahagiakan.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENFP-A",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu cerdas, kreatif, serba bisa, dan pandai bergaul, serta memiliki bakat alami dalam berwirausaha dan memimpin. Kamu juga sangat bersemangat untuk menemukan karier yang sesuai passion-mu, dan tidak akan puas dengan pilihan karier yang biasa-biasa saja. Keuangan bukanlah prioritas utama; kamu lebih memilih hidup sederhana selagi melakukan hal yang kamu sukai.\n\nDi Telkom University, kamu akan menemukan banyak sekali kesempatan untuk mengeksplorasi minat dan bakatmu yang luas. Meskipun menentukan jurusan kuliah mungkin awalnya terasa sulit karena ketertarikanmu yang beragam, kamu akan menemukan berbagai program studi yang bisa mengakomodasi kreativitas dan kemampuan artistikmu. Proses belajar di sini akan membantumu untuk menemukan passion terdalammu dan mengembangkan potensimu secara maksimal. Baik itu melalui desain, multimedia, seni pertunjukan, atau bahkan menulis, kamu dapat mengeksplorasi berbagai jalur kreatif yang sesuai dengan minatmu. Telkom University juga menyediakan berbagai fasilitas dan program pendukung untuk mengembangkan bakat artistikmu dan membantu kamu untuk mengejar karir di bidang kreatif. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nDi Telkom University, kamu akan menemukan lingkungan yang mendukung kreativitas dan inovasi.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENFP-S",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu cerdas, kreatif, dan serba bisa, punya kemampuan berinteraksi sosial yang luar biasa, dan bakat alami dalam berwirausaha serta memimpin. Kamu juga bersemangat mencari karier yang sesuai passion, dan tak akan puas dengan pilihan karier yang biasa-biasa saja. Keuangan bukanlah hal utama bagimu; kamu lebih memilih hidup sederhana selagi melakukan hal yang kamu sukai.\n\nMeskipun kamu mungkin merasa sedikit kesulitan menentukan jurusan kuliah yang sesuai dengan minatmu yang luas, di Telkom University, kamu akan menemukan banyak peluang untuk mengeksplorasi berbagai bidang studi. Ketertarikanmu pada interaksi sosial dan keinginan untuk membantu orang lain dapat disalurkan melalui berbagai program studi yang ada. Kamu bisa mengejar bidang-bidang yang berhubungan dengan teknologi dan inovasi sosial, memberikanmu kesempatan untuk menggabungkan minatmu pada teknologi dengan keinginan untuk berkontribusi pada masyarakat. Misalnya, kamu bisa berkontribusi dalam pengembangan aplikasi yang berdampak positif bagi kehidupan banyak orang, atau kamu bisa fokus pada bidang yang membantu mengatasi permasalahan sosial dengan pendekatan teknologi yang inovatif. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses belajar di Telkom University akan membantumu menemukan passion terdalammu dan mengembangkan potensimu secara maksimal. Di sini, kamu akan dibekali dengan kemampuan dan pengalaman yang dibutuhkan untuk meraih karier yang sukses dan bermanfaat bagi orang lain.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENFP-E",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu cerdas, kreatif, dan serba bisa, memiliki kemampuan komunikasi yang baik, serta bakat alami dalam berwirausaha dan kepemimpinan. Kamu juga bersemangat untuk menemukan karier yang sesuai dengan passion-mu dan tidak puas dengan pilihan karier yang biasa-biasa saja. Keuangan bukanlah prioritas utamamu; kamu lebih suka hidup sederhana selagi melakukan hal yang kamu sukai.\n\nDi Telkom University, kamu akan menemukan berbagai program studi yang sesuai dengan minat dan bakatmu yang luas. Meskipun awalnya mungkin sulit menentukan jurusan yang tepat, proses belajar di sini akan membantumu mengeksplorasi berbagai pilihan dan menemukan passion terdalammu. Kamu akan memiliki kesempatan untuk mengembangkan kemampuanmu dalam berwirausaha dan kepemimpinan melalui berbagai proyek, kegiatan ekstrakurikuler, dan kesempatan magang. Minatmu dalam menulis dan berkomunikasi akan sangat bermanfaat untuk mengembangkan karier di bidang jurnalistik, pemasaran, atau kewirausahaan. Kamu bisa mengeksplorasi berbagai bentuk kreativitas, seperti desain grafis, pembuatan konten digital, dan pengembangan aplikasi. Telkom University juga menyediakan berbagai fasilitas dan program pendukung untuk membantu kamu memulai usaha sendiri dan mengembangkan ide-ide inovatifmu. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses pembelajaran di Telkom University akan memberimu kebebasan dan fleksibilitas untuk mengejar berbagai minat, membantumu menemukan jalur karier yang sesuai dengan kepribadian dan passionmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENFP-C",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu cerdas, kreatif, serba bisa, dan pandai bergaul, serta memiliki bakat dalam berwirausaha dan memimpin. Kamu juga bersemangat menemukan karier yang sesuai dengan passion-mu, dan tak akan puas dengan pilihan karier yang biasa-biasa saja. Keuangan bukanlah hal utama; kamu lebih memilih hidup sederhana selagi melakukan apa yang kamu sukai.\n\nDi Telkom University, kamu akan menemukan berbagai program studi yang menantang dan menarik, yang memungkinkanmu mengeksplorasi berbagai minatmu. Meskipun awalnya mungkin sulit menentukan jurusan yang tepat karena ketertarikanmu yang luas, proses belajar di sini akan membantumu menemukan passion terdalammu. Kamu akan belajar untuk mengorganisir dan memanfaatkan kemampuan analitismu untuk menyelesaikan berbagai tugas dan proyek, mengembangkan kemampuan manajemen waktu dan detail yang baik. Meski pekerjaan yang bersifat administratif mungkin bukan prioritas utamamu, keterampilan organisasi dan manajemen yang terasah di Telkom University akan sangat berharga dalam segala bidang, bahkan dalam mengejar passion dan kariermu sendiri. Kemampuan ini akan membantumu untuk mengelola proyek-proyek pribadi, mengelola waktu dengan efektif, dan memastikan segala sesuatu berjalan lancar, sehingga kamu dapat fokus pada hal-hal yang benar-benar kamu sukai. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University akan membimbingmu untuk menemukan keseimbangan antara kemampuanmu yang beragam dan passionmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENTP-R",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu cerdas, serba bisa, dan memiliki beragam minat. Meskipun kamu mungkin merasa sulit untuk menentukan satu bidang studi yang tepat, di Telkom University, kamu akan menemukan banyak sekali peluang untuk mengeksplorasi berbagai bidang yang menarik bagimu. Kamu memiliki kreativitas dan kemampuan untuk berprestasi di berbagai bidang, dan kamu ingin menggunakan kemampuanmu untuk hal yang bermanfaat. Meskipun terkadang kamu merasa gelisah dan kurang puas dengan pekerjaan yang monoton, Telkom University akan membantumu menemukan passion dan jalur karir yang tepat.\n\nDi Telkom University, proses pembelajaran yang fleksibel akan memberimu kesempatan untuk mengeksplorasi berbagai bidang, mulai dari teknologi informasi hingga desain dan kewirausahaan. Kamu akan belajar untuk berpikir kritis, memecahkan masalah, dan berinovasi. Meskipun pekerjaan yang bersifat teknis dan langsung berhubungan dengan benda mungkin bukan prioritas utamamu, kemampuan untuk memecahkan masalah dan berpikir kreatif tetap bisa diasah dan diimplementasikan di berbagai bidang. Kamu dapat menggabungkan minatmu pada hal-hal yang inovatif dengan kemampuanmu dalam memecahkan masalah dan menciptakan solusi-solusi yang kreatif. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses pembelajaran di Telkom University akan membantumu untuk menemukan passion terdalammu dan mengembangkan potensimu secara maksimal, sehingga kamu dapat menemukan jalur karir yang sesuai denganmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENTP-I",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu cerdas, serba bisa, dan memiliki banyak minat. Meskipun menentukan satu bidang studi yang tepat mungkin terasa sulit, di Telkom University, kamu akan menemukan berbagai kesempatan untuk mengeksplorasi berbagai bidang yang menarik bagimu. Kamu kreatif dan ingin menggunakan kemampuanmu untuk hal-hal yang bermanfaat, dan kamu ingin memiliki kebebasan dan otonomi dalam bekerja. Meskipun terkadang kamu merasa gelisah dan kurang puas dengan pekerjaan yang terlalu terstruktur, Telkom University akan membantumu menemukan passion dan jalur karier yang tepat.\n\nDi Telkom University, kamu akan belajar untuk berpikir kritis dan analitis, mengembangkan kemampuan pemecahan masalah, serta berinovasi. Proses pembelajaran yang fleksibel akan membantumu menjelajahi berbagai bidang, dari teknologi informasi hingga ilmu-ilmu sosial. Kamu akan menemukan cara untuk menggabungkan minatmu yang luas dengan kemampuan analitis, misalnya dalam riset teknologi, pengembangan aplikasi, atau bahkan jurnalistik investigatif. Kamu akan belajar bagaimana mengelola kebebasan dan otonomi yang kamu cari, sambil tetap berkolaborasi dengan orang lain dan berkontribusi pada masyarakat. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University menyediakan lingkungan yang mendukung kreativitas dan inovasi, yang akan membantumu menemukan passion terdalammu dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENTP-A",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu cerdas, serba bisa, dan memiliki beragam minat. Meskipun menentukan satu bidang studi yang tepat mungkin terasa sulit, di Telkom University, kamu akan menemukan berbagai kesempatan untuk mengeksplorasi berbagai bidang yang menarik bagimu. Kamu sangat kreatif dan ingin menggunakan kemampuanmu untuk hal-hal yang bermanfaat, dan kamu menginginkan kebebasan dan otonomi dalam bekerja. Meskipun terkadang kamu merasa gelisah dan kurang puas dengan pekerjaan yang terlalu terstruktur, Telkom University akan membantumu menemukan passion dan jalur karier yang tepat.\n\nDi Telkom University, kamu akan belajar untuk berpikir kritis, memecahkan masalah, dan berinovasi. Proses pembelajaran yang fleksibel akan membantumu untuk menjelajahi berbagai bidang, mulai dari teknologi informasi hingga seni dan desain. Kamu dapat menggabungkan minatmu yang luas dengan kemampuan kreatifmu, misalnya dalam pengembangan aplikasi, desain grafis, atau bahkan kewirausahaan berbasis teknologi. Telkom University akan membantumu untuk menemukan keseimbangan antara kebebasan dan struktur, sehingga kamu dapat mengeksplorasi potensimu secara maksimal, sambil tetap mencapai tujuanmu. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses pembelajaran di Telkom University akan membantumu untuk menemukan passion terdalammu dan mengembangkan potensimu secara maksimal, sehingga kamu dapat menemukan jalur karier yang sesuai denganmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENTP-S",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu cerdas, serba bisa, dan memiliki banyak minat. Memilih jurusan kuliah mungkin terasa sulit karena kamu punya banyak ketertarikan, tapi di Telkom University, kamu akan menemukan berbagai kesempatan untuk mengeksplorasi bidang-bidang yang menarik. Kamu kreatif dan ingin berkontribusi, dan mencari pekerjaan yang memberimu kepuasan dan memungkinkanmu mengembangkan kemampuanmu. Kamu juga menyukai kebebasan dan otonomi dalam bekerja, dan kurang menyukai aturan yang terlalu kaku. Di Telkom University, kamu akan menemukan cara untuk menggabungkan semua hal ini.\n\nDi Telkom University, kamu akan belajar berpikir kritis, memecahkan masalah, dan berinovasi. Proses pembelajaran yang fleksibel akan membantumu menjelajahi berbagai bidang, dari teknologi informasi hingga ilmu-ilmu sosial dan humaniora. Kamu akan menemukan bagaimana menggabungkan minatmu untuk berinteraksi dengan orang lain dengan kemampuanmu untuk berinovasi dan berpikir kritis. Meskipun pekerjaan yang fokus pada interaksi emosional mungkin bukan yang paling cocok, kamu akan belajar bagaimana menggunakan kemampuan komunikasimu yang baik untuk berkolaborasi, memberikan presentasi, dan memimpin tim. Kamu akan menemukan cara untuk berkontribusi dan membuat dampak positif bagi masyarakat, sambil tetap mempertahankan kebebasan dan otonomi dalam bekerja. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses belajar di Telkom University akan membantumu menemukan passion terdalam dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENTP-E",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu cerdas, serba bisa, dan punya banyak minat! Memilih jurusan kuliah mungkin terasa sulit karena kamu punya banyak ketertarikan, tapi jangan khawatir! Di Telkom University, kamu akan menemukan berbagai kesempatan untuk mengeksplorasi bidang-bidang yang menarik minatmu. Kamu kreatif, ingin berkontribusi, dan mencari pekerjaan yang memberimu kepuasan serta memungkinkanmu mengembangkan kemampuanmu. Kamu juga menyukai kebebasan dan otonomi dalam bekerja, dan kurang menyukai aturan yang terlalu kaku. Di Telkom University, semua itu bisa kamu temukan!\n\nDi Telkom University, kamu akan belajar untuk berpikir kritis, memecahkan masalah, dan berinovasi. Proses pembelajaran yang fleksibel akan membantumu menjelajahi berbagai bidang, dari teknologi informasi hingga kewirausahaan. Minatmu yang luas akan terakomodasi dengan baik, dan kamu bisa menggabungkan kemampuanmu untuk berpikir kreatif dan strategis dengan kemampuanmu dalam berkomunikasi dan berinteraksi. Kamu bisa mengeksplorasi berbagai jalur karier, seperti jurnalistik, pemasaran, atau bahkan membangun usaha sendiri. Telkom University akan memberimu bekal kemampuan dan jaringan yang luas untuk mendukung cita-citamu. Kamu akan belajar bagaimana mengelola kebebasan dan otonomi yang kamu cari, sambil tetap mencapai tujuan dan berkontribusi pada masyarakat. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses belajar di Telkom University akan membantumu menemukan passion terdalam dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENTP-C",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu cerdas dan punya banyak minat! Memilih jurusan kuliah mungkin terasa sulit karena kamu punya banyak ketertarikan, tapi di Telkom University, kamu akan menemukan berbagai kesempatan untuk mengeksplorasi bidang-bidang yang menarik. Kamu kreatif, ingin berkontribusi, dan mencari pekerjaan yang memberimu kepuasan dan memungkinkanmu mengembangkan kemampuanmu. Kamu juga menyukai kebebasan dan otonomi dalam bekerja, dan kurang menyukai aturan yang terlalu kaku. Di Telkom University, semua itu bisa kamu temukan!\n\nDi Telkom University, kamu akan belajar berpikir kritis, memecahkan masalah, dan berinovasi. Proses pembelajaran yang fleksibel akan membantumu menjelajahi berbagai bidang, dari teknologi informasi hingga ilmu-ilmu sosial. Meskipun pekerjaan administratif mungkin bukan prioritas utamamu, kamu akan belajar keterampilan organisasi dan manajemen yang penting untuk mengelola proyek dan waktu secara efektif. Keterampilan ini akan sangat berguna, bahkan dalam mengejar passion dan karier yang kamu sukai. Telkom University akan melatihmu untuk menyeimbangkan kreativitas dan kebebasan dengan struktur dan kedisiplinan yang dibutuhkan untuk sukses. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses belajar di Telkom University akan membantumu menemukan passion terdalam dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENFJ-R",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu memiliki kemampuan luar biasa dalam berinteraksi dengan orang lain dan senang membantu sesama mencapai potensi terbaiknya. Kamu kreatif dan berorientasi pada tujuan, serta memiliki semangat untuk berkontribusi dan membuat perbedaan positif dalam kehidupan orang lain. Meskipun dunia kerja modern mungkin terkadang terasa kurang sesuai dengan pendekatanmu yang lebih humanis, Telkom University akan membantumu menemukan cara untuk menggabungkan minatmu dengan dunia profesional yang dinamis.\n\nDi Telkom University, kamu akan belajar bagaimana mengaplikasikan kemampuanmu dalam berbagai bidang, baik yang berhubungan langsung dengan interaksi sosial maupun yang membutuhkan kreativitas dan kemampuan teknis. Meskipun pekerjaan yang bersifat sangat teknis dan praktis mungkin bukan yang paling cocok untukmu, kamu akan belajar keterampilan manajemen, kepemimpinan, dan kerja sama tim yang akan sangat berharga dalam segala bidang. Kamu akan mempelajari cara untuk memberikan dampak positif, baik melalui inovasi teknologi maupun melalui kepemimpinan yang inspiratif. Telkom University akan memberimu kesempatan untuk berkolaborasi, mengembangkan kemampuanmu, dan menemukan jalur karier yang sesuai dengan nilai-nilai dan passion-mu. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nDi Telkom University, kamu akan menemukan lingkungan yang mendukung dan menantang, yang akan membantumu untuk berkembang dan mencapai potensi terbaikmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENFJ-I",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu memiliki kemampuan luar biasa dalam berinteraksi dengan orang lain dan senang membantu mereka mencapai potensi terbaiknya. Kamu juga kreatif dan berorientasi pada tujuan, serta memiliki semangat untuk berkontribusi dan membuat perbedaan positif. Meskipun dunia kerja modern mungkin terkadang terasa kurang sesuai dengan pendekatanmu yang lebih humanis, Telkom University akan membantumu menemukan cara untuk menggabungkan minatmu dengan dunia profesional yang dinamis.\n\nDi Telkom University, kamu akan belajar bagaimana mengaplikasikan kemampuanmu di berbagai bidang, baik yang berhubungan langsung dengan interaksi sosial maupun yang membutuhkan analisis dan pemecahan masalah. Meskipun pekerjaan yang sangat menekankan aspek teknis dan ilmiah mungkin bukan yang paling cocok untukmu, kamu akan belajar keterampilan manajemen, kepemimpinan, dan kerja sama tim yang sangat berharga. Kamu akan mempelajari bagaimana menggabungkan kemampuanmu dalam memahami orang lain dengan kemampuan analitis untuk memecahkan masalah kompleks dan memberikan solusi inovatif. Telkom University menyediakan beragam program studi yang akan membantumu menemukan jalur karier yang sesuai dengan nilai-nilai dan passion-mu. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses pembelajaran di Telkom University akan memberimu kesempatan untuk mengembangkan potensimu secara maksimal, menemukan cara untuk menggabungkan minatmu pada interaksi sosial dengan kemampuan analisis.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENFJ-A",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu punya kemampuan luar biasa dalam berinteraksi dengan orang lain dan senang membantu mereka berkembang. Kamu juga sangat kreatif dan punya banyak ide menarik! Kamu adalah pribadi yang berorientasi pada tujuan dan selalu ingin mencapai sesuatu yang berarti. Meskipun terkadang kamu merasa tantangan untuk menemukan jalur karier yang tepat, di Telkom University, kamu akan menemukan banyak kesempatan untuk mengembangkan potensi dan bakatmu!\n\nDi Telkom University, kamu akan belajar bagaimana mengaplikasikan kemampuanmu dalam berbagai bidang, baik yang berhubungan langsung dengan interaksi sosial maupun yang membutuhkan kreativitas. Kamu akan mengembangkan kemampuan kepemimpinan, manajemen, dan kerja sama tim yang sangat berharga dalam dunia kerja modern. Kamu juga akan memiliki kesempatan untuk mengeksplorasi minatmu di bidang seni dan humaniora. Telkom University menyediakan beragam program studi yang akan membantumu menemukan jalur karier yang sesuai dengan nilai-nilai dan passion-mu. Kamu akan belajar bagaimana menggabungkan bakat artistikmu dengan kemampuan interpersonalmu untuk menciptakan inovasi dan memberikan dampak positif bagi masyarakat. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses pembelajaran di Telkom University akan memberimu kesempatan untuk berkembang dan mencapai potensi terbaikmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENFJ-S",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu punya kemampuan luar biasa dalam berinteraksi dengan orang lain dan senang membantu mereka mencapai potensi terbaiknya. Kamu juga kreatif dan berorientasi pada tujuan, selalu ingin mencapai sesuatu yang berarti. Kamu memiliki semangat untuk berkontribusi dan membuat perbedaan positif dalam kehidupan orang lain. Meskipun terkadang kamu merasa kesulitan dalam memilih jalur karier yang tepat, Telkom University akan membantumu menemukan kesempatan untuk mengembangkan potensi dan bakatmu!\n\nDi Telkom University, kamu akan belajar bagaimana mengaplikasikan kemampuanmu dalam berbagai bidang yang sesuai dengan minatmu. Kamu akan mengembangkan kemampuan kepemimpinan, manajemen, dan kerja sama tim. Telkom University menyediakan beragam program studi yang akan membantumu menemukan jalur karier yang sesuai dengan nilai-nilai dan passion-mu. Kamu akan belajar bagaimana menggabungkan kemampuanmu dalam memahami orang lain dengan keterampilan untuk memecahkan masalah dan berinovasi. Proses pembelajaran di Telkom University akan mempersiapkanmu untuk menghadapi tantangan dunia kerja modern yang dinamis, sambil tetap mempertahankan nilai-nilai humanis dan kepedulian terhadap sesama. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses belajar di Telkom University akan memberimu kesempatan untuk berkembang dan mencapai potensi terbaikmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENFJ-E",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu memiliki kemampuan luar biasa dalam berinteraksi dengan orang lain dan senang membantu mereka berkembang. Kamu juga kreatif dan berorientasi pada tujuan, selalu ingin mencapai sesuatu yang berarti. Kamu memiliki semangat untuk berkontribusi dan membuat perbedaan positif dalam kehidupan orang lain. Meskipun terkadang kamu merasa kesulitan dalam memilih jalur karier yang tepat, di Telkom University, kamu akan menemukan banyak kesempatan untuk mengembangkan potensi dan bakatmu!\n\nDi Telkom University, kamu akan belajar bagaimana mengaplikasikan kemampuanmu di berbagai bidang. Kamu akan mengembangkan kemampuan kepemimpinan, manajemen, dan kerja sama tim yang sangat berharga. Telkom University menyediakan beragam program studi yang akan membantumu menemukan jalur karier yang sesuai dengan nilai-nilai dan passion-mu. Kamu akan belajar bagaimana menggabungkan kemampuanmu dalam memahami orang lain dengan keterampilan komunikasi dan presentasi yang kuat, untuk memimpin dan menginspirasi orang lain. Meskipun karier di bidang penjualan dan pemasaran mungkin bukan yang paling sesuai, kamu akan menemukan bagaimana kemampuan komunikasimu dapat dimaksimalkan di berbagai bidang, seperti hubungan masyarakat atau bahkan dalam memimpin tim di bidang teknologi. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses pembelajaran di Telkom University akan memberimu kesempatan untuk berkembang dan mencapai potensi terbaikmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ENFJ-C",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu memiliki kemampuan luar biasa dalam berinteraksi dengan orang lain dan senang membantu mereka mencapai potensi terbaiknya. Kamu juga kreatif dan berorientasi pada tujuan, selalu ingin mencapai sesuatu yang berarti. Kamu memiliki semangat untuk berkontribusi dan membuat perbedaan positif dalam kehidupan orang lain. Meskipun terkadang kamu merasa kesulitan dalam memilih jalur karier yang tepat, di Telkom University, kamu akan menemukan banyak kesempatan untuk mengembangkan potensi dan bakatmu!\n\nDi Telkom University, kamu akan belajar bagaimana mengaplikasikan kemampuanmu di berbagai bidang. Kamu akan mengembangkan kemampuan kepemimpinan, manajemen, dan kerja sama tim yang sangat berharga. Telkom University menyediakan beragam program studi yang akan membantumu menemukan jalur karier yang sesuai dengan nilai-nilai dan passion-mu. Meskipun karier yang sangat administratif mungkin bukan prioritas utamamu, kamu akan belajar keterampilan organisasi dan manajemen yang penting untuk mengelola proyek dan waktu secara efektif. Keterampilan ini akan sangat berguna, bahkan dalam mengejar passion dan karier yang kamu sukai. Telkom University akan melatihmu untuk menyeimbangkan kreativitas dan kemampuan interpersonalmu dengan struktur dan kedisiplinan yang dibutuhkan untuk sukses. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nProses belajar di Telkom University akan memberimu kesempatan untuk berkembang dan mencapai potensi terbaikmu.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ESTP-R",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu adalah seorang yang menyukai aktivitas fisik dan kegiatan yang menantang. Kamu senang belajar melalui pengalaman langsung dan mengembangkan keterampilan praktis. Meskipun memilih jurusan kuliah mungkin terasa sulit karena ketertarikanmu yang beragam, Telkom University menawarkan berbagai program studi yang akan membantumu mengasah kemampuan dan minatmu.\n\nDi Telkom University, kamu akan menemukan berbagai kesempatan untuk belajar sambil melakukan kegiatan yang praktis dan menantang. Kamu bisa mengeksplorasi berbagai bidang studi yang memungkinkanmu untuk menerapkan kemampuan praktis dan analitis, serta mengembangkan strategi dan keterampilan pemecahan masalah. Baik itu melalui proyek-proyek yang membutuhkan keterampilan teknis, magang di perusahaan, atau kegiatan ekstrakurikuler, kamu akan menemukan cara untuk menggabungkan minatmu dengan pembelajaran akademis. Meskipun pekerjaan yang membutuhkan banyak interaksi sosial mungkin bukan yang paling sesuai untukmu, kamu akan belajar untuk bekerja sama dalam tim dan berkomunikasi secara efektif untuk mencapai tujuan bersama. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University menyediakan lingkungan belajar yang dinamis dan mendukung, yang akan membantumu menemukan passion dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    },
    {
        codeMbti: "ESTP-I",
        naration: "Sebagai calon mahasiswa Telkom University, Kamu adalah seorang yang menyukai aktivitas fisik dan kegiatan yang menantang. Kamu senang belajar melalui pengalaman langsung dan mengembangkan keterampilan praktis. Meskipun memilih jurusan kuliah mungkin terasa sulit karena ketertarikanmu yang beragam, Telkom University menawarkan berbagai program studi yang akan membantumu mengasah kemampuan dan minatmu.\n\nDi Telkom University, kamu akan menemukan berbagai kesempatan untuk belajar sambil melakukan kegiatan yang praktis dan menantang. Kamu bisa mengeksplorasi berbagai bidang studi yang memungkinkanmu untuk menerapkan kemampuan praktis dan analitis, serta mengembangkan strategi dan keterampilan pemecahan masalah. Baik itu melalui proyek-proyek yang membutuhkan keterampilan teknis, magang di perusahaan, atau kegiatan ekstrakurikuler, kamu akan menemukan cara untuk menggabungkan minatmu dengan pembelajaran akademis. Meskipun pekerjaan yang membutuhkan banyak interaksi sosial mungkin bukan yang paling sesuai untukmu, kamu akan belajar untuk bekerja sama dalam tim dan berkomunikasi secara efektif untuk mencapai tujuan bersama. Kamu juga akan mengembangkan kemampuan untuk menganalisis data dan informasi secara mendalam, untuk mendukung proses pengambilan keputusan yang efektif. Kami sudah mengidentifikasi kekuatan kamu, dan beberapa pilihan program studi berikut ini adalah yang sesuai dengan minat dan kepribadian kamu, yaitu :\n\nTelkom University menyediakan lingkungan belajar yang dinamis dan mendukung, yang akan membantumu menemukan passion dan mengembangkan potensimu secara maksimal.\n\nMari wujudkan masa depan dan kariermu bersama Telkom University! Sampai jumpa di kampus!"
    }
];
